(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"_300x250.jpg", id:"_300x250"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._300x250 = function() {
	this.initialize(img._300x250);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.twoyears = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D9C993").s().p("ATLBkQgKgDgJgHQgIgHgHgLQgGgLgEgOIAmgIQACAIADAHQADAGAFAEQAHAIAKAAQAKAAAHgHQAHgGAAgLQAAgHgEgGQgDgFgGgFQgGgFgZgNIgPgIQgJgFgFgGQgHgHgCgIQgEgIAAgLQAAgNAEgKQADgLAIgHQAHgHAMgEQAMgEAOAAQANAAALAEQAKADAIAHQAIAGAEAJQAGAJACALIgiAKQgFgOgHgHQgHgGgKAAQgKAAgGAGQgFAFAAALQAAAFAEAFQADAEAGAFIAfARIAPAKQAJAEAFAGQAGAIAEAJQADAKAAALQABANgFALQgFAKgHAIQgJAHgMAEQgMAEgPAAQgMAAgKgDgAQwBkQgLgDgJgHQgIgHgGgLQgHgLgDgOIAmgIQABAIADAHQADAGAFAEQAHAIAKAAQALAAAGgHQAIgGAAgLQAAgHgFgGQgDgFgGgFQgGgFgYgNIgQgIQgIgFgFgGQgHgHgDgIQgEgIAAgLQAAgNAEgKQAEgLAHgHQAIgHALgEQAMgEAPAAQAMAAALAEQAKADAJAHQAHAGAFAJQAFAJADALIgjAKQgFgOgGgHQgHgGgKAAQgKAAgGAGQgGAFABALQAAAFADAFQADAEAHAFIAeARIAPAKQAJAEAGAGQAGAIAEAJQADAKAAALQAAANgEALQgFAKgIAIQgJAHgLAEQgMAEgQAAQgMAAgJgDgAGhBkQgMgEgIgIQgJgIgFgNQgEgNAAgSIAAhHQAAgSAEgNQAFgNAJgIQAIgIAMgEQALgDAPAAQAOAAAMADQALAEAJAIQAIAIAFANQAEANABASIAABHQgBASgEANQgFANgIAIQgJAIgLAEQgMADgOAAQgPAAgLgDgAGpg+QgEADgCAGQgBAFAAAJIAABQQAAAIABAGQACAFAEAEQAFAFANAAQAMAAAHgFQACgEACgFQACgGAAgIIAAhQQAAgJgCgFQgCgGgCgDQgHgGgMAAQgNAAgFAGgAC4BkQgKgDgJgHQgIgHgHgLQgGgLgEgOIAmgIQACAIADAHQADAGAFAEQAHAIAKAAQALAAAGgHQAHgGAAgLQAAgHgEgGQgDgFgGgFQgGgFgZgNIgPgIQgIgFgGgGQgHgHgDgIQgDgIAAgLQAAgNADgKQAEgLAIgHQAHgHAMgEQALgEAPAAQANAAAKAEQALADAIAHQAHAGAFAJQAGAJACALIgiAKQgFgOgHgHQgHgGgKAAQgJAAgGAGQgGAFAAALQAAAFAEAFQADAEAGAFIAfARIAPAKQAJAEAFAGQAGAIAEAJQAEAKAAALQAAANgFALQgFAKgHAIQgJAHgMAEQgMAEgPAAQgMAAgKgDgAqQBkQgMgEgIgIQgJgIgEgNQgFgNAAgSIAAhHQAAgSAFgNQAEgNAJgIQAIgIAMgEQAMgDAOAAQAOAAALADQAMAEAJAIQAJAIAEANQAFANgBASIAABHQABASgFANQgEANgJAIQgJAIgMAEQgLADgOAAQgOAAgMgDgAqJg+QgDADgBAGQgCAFgBAJIAABQQABAIACAGQABAFADAEQAHAFAMAAQAMAAAGgFQAEgEACgFQABgGAAgIIAAhQQAAgJgBgFQgCgGgEgDQgGgGgMAAQgMAAgHAGgAVFBlIAAgoIAoAAIAAAogAOABlIAAjIIBqAAIAAAiIhEAAIAAAuIAzAAIAAAgIgzAAIAAA2IBGAAIAAAigAMEBlIAAjIIAnAAIAACmIA9AAIAAAigAJ0BlIghhTIgSAAIAABTIgnAAIAAjIIA4AAQARAAANAEQANAEAIAIQAJAHAFAMQADALAAAOQABAKgCAIQgCAIgEAGQgEAHgFADQgGAFgIADIAmBagAJBgMIAUAAQAMAAAHgGQAEgEACgFQACgFAAgHQAAgIgCgFQgCgFgEgEQgHgGgMAAIgUAAgABTBlIgihTIgSAAIAABTIgkAAIAAjIIA2AAQAQAAANAEQANAEAJAIQAIAHAFAMQAEALAAAOQAAAKgCAIQgCAIgDAGQgEAHgFADQgHAFgIADIAmBagAAfgMIAUAAQANAAAHgGQADgEADgFQABgFAAgHQAAgIgBgFQgDgFgDgEQgHgGgNAAIgUAAgAhABlIgJgrIg2AAIgLArIglAAIAyjIIAyAAIAwDIgAhSAYIgShQIgBAAIgTBQIAmAAgAktBlIAAjIIBqAAIAAAiIhEAAIAAAuIA0AAIAAAgIg0AAIAAA2IBHAAIAAAigAmgBlIAAhSIg3h2IAqAAIAhBRIAhhRIAqAAIg4B2IAABSgAscBlIgciJIgBAAIgfCJIglAAIgqjIIAkAAIAbCCIABAAIAciCIAlAAIAcCCIABAAIAbiCIAkAAIgtDIgAwGBlIAAimIgtAAIAAgiICAAAIAAAiIgtAAIAACmgAzABlIg6iBIgBAAIAACBIgjAAIAAjIIAqAAIA1B1IABAAIAAh1IAjAAIAADIgA1sBlIAAjIIAmAAIAADIg");
	this.shape.setTransform(0,-3.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AChhXQgIAHgEALQgEAKAAANQAAALAEAIQADAIAHAHQAFAGAJAFIAQAIQAYANAGAFQAGAFADAFQAEAGAAAHQAAALgHAGQgGAHgLAAQgKAAgIgIQgEgEgDgGQgEgHgBgIIgmAIQADAOAHALQAGALAJAHQAJAHAKADQAKADAMAAQAPAAANgEQALgEAJgHQAHgIAFgKQAFgLAAgNQAAgLgEgKQgDgJgHgIQgGgGgIgEIgQgKQgVgMgJgFQgGgFgDgEQgEgFAAgFQAAgLAFgFQAGgGAKAAQAKAAAHAGQAHAHAFAOIAjgKQgDgLgFgJQgGgJgHgGQgIgHgLgDQgKgEgNAAQgPAAgLAEQgLAEgIAHgAAwhjIg2AAIAADIIAlAAIAAhTIASAAIAiBTIApAAIgmhaQAIgDAGgFQAGgDAEgHQADgGACgIQACgIAAgKQAAgOgEgLQgFgMgIgHQgJgIgNgEQgNgEgRAAgABHg9QADAEACAFQACAFAAAIQAAAHgCAFQgCAFgDAEQgHAGgNAAIgUAAIAAg3IAUAAQANAAAHAGgAF7AkQAAASAFANQAEANAJAIQAIAIAMAEQAMADAOAAQAPAAALgDQALgEAJgIQAJgIAEgNQAEgNAAgSIAAhHQAAgSgEgNQgEgNgJgIQgJgIgLgEQgLgDgPAAQgOAAgMADQgMAEgIAIQgJAIgEANQgFANAAASgAIahjIAADIIAnAAIAAhTIASAAIAiBTIApAAIgmhaQAIgDAGgFQAGgDAEgHQADgGACgIQACgIAAgKQAAgOgFgLQgEgMgIgHQgJgIgNgEQgNgEgRAAgAHUgnIAABQQAAAIgCAGQgBAFgEAEQgGAFgMAAQgNAAgFgFQgEgEgBgFQgCgGAAgIIAAhQQAAgJACgFQABgGAEgDQAFgGANAAQAMAAAGAGQAEADABAGQACAFAAAJgAJVhDQANAAAHAGQADAEACAFQACAFAAAIQAAAHgCAFQgCAFgDAEQgHAGgNAAIgUAAIAAg3gAOnhBIBDAAIAAgiIhqAAIAADIIBtAAIAAgiIhGAAIAAg2IAzAAIAAggIgzAAgARdhiQgKgEgNAAQgPAAgLAEQgMAEgHAHQgIAHgEALQgEAKAAANQAAALAEAIQADAIAHAHQAFAGAJAFIAPAIQAZANAFAFQAHAFADAFQAEAGAAAHQAAALgHAGQgHAHgKAAQgKAAgIgIQgEgEgDgGQgEgHgBgIIgmAIQADAOAHALQAGALAJAHQAIAHALADQAKADAMAAQAPAAAMgEQAMgEAIgHQAIgIAFgKQAEgLAAgNQAAgLgDgKQgEgJgGgIQgGgGgIgEIgQgKQgVgMgJgFQgGgFgDgEQgEgFAAgFQAAgLAFgFQAGgGAKAAQAKAAAHAGQAHAHAFAOIAigKQgCgLgGgJQgFgJgHgGQgIgHgLgDgASygMQAGAGAIAFIAQAIQAYANAGAFQAGAFADAFQAEAGAAAHQAAALgHAGQgGAHgLAAQgKAAgHgIQgFgEgDgGQgDgHgCgIIgmAIQAEAOAHALQAGALAIAHQAJAHAKADQAKADAMAAQAPAAANgEQALgEAJgHQAIgIAEgKQAEgLAAgNQAAgLgDgKQgDgJgHgIQgFgGgJgEIgPgKQgWgMgIgFQgHgFgDgEQgEgFAAgFQAAgLAGgFQAGgGAKAAQAKAAAGAGQAHAHAFAOIAjgKQgDgLgGgJQgFgJgHgGQgIgHgKgDQgLgEgMAAQgPAAgMAEQgLAEgIAHQgHAHgEALQgEAKAAANQAAALAEAIQADAIAGAHgAMEhjIAADIIBlAAIAAgiIg+AAIAAimgAVtA9IgoAAIAAAoIAoAAgA0fhjIAADIIAkAAIAAiBIAAAAIA7CBIAlAAIAAjIIgjAAIAAB1IgBAAIg1h1gA1shjIAADIIAmAAIAAjIgAw0hBIAtAAIAACmIAnAAIAAimIAtAAIAAgiIiBAAgAunhjIAqDIIAlAAIAfiJIABAAIAcCJIAlAAIAsjIIgkAAIgbCCIAAAAIgciCIglAAIgcCCIgBAAIgbiCgAqkhXQgJAIgFANQgEANAAASIAABHQAAASAEANQAFANAJAIQAIAIAMAEQALADAPAAQAOAAALgDQAMgEAJgIQAIgIAFgNQAEgNAAgSIAAhHQAAgSgEgNQgFgNgIgIQgJgIgMgEQgLgDgOAAQgPAAgLADQgMAEgIAIgApfg1QACAFAAAJIAABQQAAAIgCAGQgCAFgDAEQgGAFgMAAQgNAAgGgFQgDgEgCgFQgCgGAAgIIAAhQQAAgJACgFQACgGADgDQAGgGANAAQAMAAAGAGQADADACAGgAmgATIAABSIAnAAIAAhSIA3h2IgpAAIghBRIgihRIgpAAgAjUANIAAggIgzAAIAAguIBDAAIAAgiIhpAAIAADIIBsAAIAAgiIhGAAIAAg2gAhlg4IABAAIASBQIgmAAgAh9hjIgyDIIAlAAIALgrIA2AAIAJArIAlAAIgwjIg");
	this.shape_1.setTransform(0,-3.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ATLBkQgKgDgJgHQgIgHgHgLQgGgLgEgOIAmgIQACAIADAHQADAGAFAEQAHAIAKAAQAKAAAHgHQAHgGAAgLQAAgHgEgGQgDgFgGgFQgGgFgZgNIgPgIQgJgFgFgGQgHgHgCgIQgEgIAAgLQAAgNAEgKQADgLAIgHQAHgHAMgEQAMgEAOAAQANAAALAEQAKADAIAHQAIAGAEAJQAGAJACALIgiAKQgFgOgHgHQgHgGgKAAQgKAAgGAGQgFAFAAALQAAAFAEAFQADAEAGAFIAfARIAPAKQAJAEAFAGQAGAIAEAJQADAKAAALQABANgFALQgFAKgHAIQgJAHgMAEQgMAEgPAAQgMAAgKgDgAQwBkQgLgDgJgHQgIgHgGgLQgHgLgDgOIAmgIQABAIADAHQADAGAFAEQAHAIAKAAQALAAAGgHQAIgGAAgLQAAgHgFgGQgDgFgGgFQgGgFgYgNIgQgIQgIgFgFgGQgHgHgDgIQgEgIAAgLQAAgNAEgKQAEgLAHgHQAIgHALgEQAMgEAPAAQAMAAALAEQAKADAJAHQAHAGAFAJQAFAJADALIgjAKQgFgOgGgHQgHgGgKAAQgKAAgGAGQgGAFABALQAAAFADAFQADAEAHAFIAeARIAPAKQAJAEAGAGQAGAIAEAJQADAKAAALQAAANgEALQgFAKgIAIQgJAHgLAEQgMAEgQAAQgMAAgJgDgAGhBkQgMgEgIgIQgJgIgFgNQgEgNAAgSIAAhHQAAgSAEgNQAFgNAJgIQAIgIAMgEQALgDAPAAQAOAAAMADQALAEAJAIQAIAIAFANQAEANABASIAABHQgBASgEANQgFANgIAIQgJAIgLAEQgMADgOAAQgPAAgLgDgAGpg+QgEADgCAGQgBAFAAAJIAABQQAAAIABAGQACAFAEAEQAFAFANAAQAMAAAHgFQACgEACgFQACgGAAgIIAAhQQAAgJgCgFQgCgGgCgDQgHgGgMAAQgNAAgFAGgAC4BkQgKgDgJgHQgIgHgHgLQgGgLgEgOIAmgIQACAIADAHQADAGAFAEQAHAIAKAAQALAAAGgHQAHgGAAgLQAAgHgEgGQgDgFgGgFQgGgFgZgNIgPgIQgIgFgGgGQgHgHgDgIQgDgIAAgLQAAgNADgKQAEgLAIgHQAHgHAMgEQALgEAPAAQANAAAKAEQALADAIAHQAHAGAFAJQAGAJACALIgiAKQgFgOgHgHQgHgGgKAAQgJAAgGAGQgGAFAAALQAAAFAEAFQADAEAGAFIAfARIAPAKQAJAEAFAGQAGAIAEAJQAEAKAAALQAAANgFALQgFAKgHAIQgJAHgMAEQgMAEgPAAQgMAAgKgDgAqQBkQgMgEgIgIQgJgIgEgNQgFgNAAgSIAAhHQAAgSAFgNQAEgNAJgIQAIgIAMgEQAMgDAOAAQAOAAALADQAMAEAJAIQAJAIAEANQAFANgBASIAABHQABASgFANQgEANgJAIQgJAIgMAEQgLADgOAAQgOAAgMgDgAqJg+QgDADgBAGQgCAFgBAJIAABQQABAIACAGQABAFADAEQAHAFAMAAQAMAAAGgFQAEgEACgFQABgGAAgIIAAhQQAAgJgBgFQgCgGgEgDQgGgGgMAAQgMAAgHAGgAVFBlIAAgoIAoAAIAAAogAOABlIAAjIIBqAAIAAAiIhEAAIAAAuIAzAAIAAAgIgzAAIAAA2IBGAAIAAAigAMEBlIAAjIIAnAAIAACmIA9AAIAAAigAJ0BlIghhTIgSAAIAABTIgnAAIAAjIIA4AAQARAAANAEQANAEAIAIQAJAHAFAMQADALAAAOQABAKgCAIQgCAIgEAGQgEAHgFADQgGAFgIADIAmBagAJBgMIAUAAQAMAAAHgGQAEgEACgFQACgFAAgHQAAgIgCgFQgCgFgEgEQgHgGgMAAIgUAAgABTBlIgihTIgSAAIAABTIgkAAIAAjIIA2AAQAQAAANAEQANAEAJAIQAIAHAFAMQAEALAAAOQAAAKgCAIQgCAIgDAGQgEAHgFADQgHAFgIADIAmBagAAfgMIAUAAQANAAAHgGQADgEADgFQABgFAAgHQAAgIgBgFQgDgFgDgEQgHgGgNAAIgUAAgAhABlIgJgrIg2AAIgLArIglAAIAyjIIAyAAIAwDIgAhSAYIgShQIgBAAIgTBQIAmAAgAktBlIAAjIIBqAAIAAAiIhEAAIAAAuIA0AAIAAAgIg0AAIAAA2IBHAAIAAAigAmgBlIAAhSIg3h2IAqAAIAhBRIAhhRIAqAAIg4B2IAABSgAscBlIgciJIgBAAIgfCJIglAAIgqjIIAkAAIAbCCIABAAIAciCIAlAAIAcCCIABAAIAbiCIAkAAIgtDIgAwGBlIAAimIgtAAIAAgiICAAAIAAAiIgtAAIAACmgAzABlIg6iBIgBAAIAACBIgjAAIAAjIIAqAAIA1B1IABAAIAAh1IAjAAIAADIgA1sBlIAAjIIAmAAIAADIg");
	this.shape_2.setTransform(0,-3.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140,-15.3,279.9,22.9);


(lib.Symbol17 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2C4F67").s().p("ApACJQAKgHARgQQAQgRgKAHIgCABQgOAHgrAHQgMgMgLgPQAfgIAfgTQARgKAJgIQgnAMgfABQgWABgPgEQgJgbgBgcQAbAoBBgdQAhgNAbgVQBBgPAtAIQAWAEAJAHQgHhDhGAZQgVAIgZAQQgWAPAEgBQhBAPgqACQgeACgPgFQACgdALgaQAcAjA4gXQAfgMAdgYQBLgPAuAHQAeAEAMAMQAUAmAAAoQAABEgyAxQgyAxhGAAQg3AAglgdgAmxBpQgJgygxARQgOAFgQALQgPALAEgBQAvgJAeAHQAQAEAGAFIAAAAgAnSAGQgXAJgaARQgOAIgIAHQBSgRArAGQAXADAGAGQgGgtgnAAQgQAAgWAGgADxCZIAAgHIADAAQAFAAABgDIABgEIgKgiIAJAAIAFAWIAAAAIAGgWIAJAAIgLAjQgDAIgDADQgDACgFAAgABJCRQABgHAGAAIgDgCQgBAAAAgBQgBAAAAAAQAAgBAAgBQgBAAAAgBQABgEAFgCQgFgEAAgFQAAgFAEgEQADgEAHAAQAFAAAEADQACgDAGAAIAAAGIgGABQACACAAAEQAAAFgDADQgEAEgGAAQgGAAgBACQAAACAMABQAMABAAAIQAAAEgFADQgDADgJAAQgPAAgBgIgABRCQQAAAEAKAAQADAAADgCQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAQAAgEgKAAQgHAAAAAEgABUBwQAAABAAAAQAAAAgBABQAAAAAAABQAAABAAAAQAAAGAGAAQAGAAAAgGQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAQAAABgBAAgAAjCXIADgLIgEAAIAAgJIAKAAIAAAJIgFALgAGnCIQgFgFABgIQgBgJAFgFQAEgFAHAAQAHAAAEAFQAEAFAAAHIAAADIgVAAQAAAKAGAAQAFAAADgEIAHAEQgFAHgKAAQgHAAgEgFgAGsB2IANAAQgBgIgGAAQgHAAABAIgAFrCIQgEgFAAgIQAAgJAEgFQAFgFAHAAQAHAAAEAFQADAFAAAHIAAADIgVAAQAAAKAHAAQAFAAADgEIAGAEQgFAHgJAAQgHAAgFgFgAFwB2IANAAQAAgIgGAAQgHAAAAAIgACqCKQgDgDAAgDQAAgMAUgCIAAgDQAAgFgFAAQgFAAgDAFIgFgEQABgDAEgCQAEgCAEAAQAHABADADQAEADAAAHIAAARIABAFIgJAAIAAgDQgGAEgFAAQgFAAgCgDgACzB+QgDABAAADQAAAFADAAQAEAAAEgEIAAgIIgIADgAByCIQgFgFAAgIQAAgJAFgFQAEgFAHAAQAIAAADAFQAFAFAAAJQAAAIgFAFQgDAFgIAAQgHAAgEgFgAB2B7QABALAGAAQAHAAAAgLQAAgMgHAAQgGAAgBAMgAAACIQgDgFgBgIQABgJADgFQADgFAHAAQAHAAAEAFQADAFABAHIAAADIgWAAQABAKAGAAQAFAAADgEIAHAEQgGAHgKAAQgGAAgDgFgAADB2IAOAAQgBgIgGAAQgHAAAAAIgAg7CIQgEgFAAgIQAAgJAEgFQAEgFAIAAQAGAAAFAFQADAFAAAHIAAADIgVAAQAAAKAHAAQAEAAAEgEIAGAEQgFAHgJAAQgIAAgEgFgAg2B2IANAAQAAgIgGAAQgHAAAAAIgAjWCIQgDgFAAgIQAAgJADgFQAFgFAHAAQAHAAAFAFQADAFAAAJQAAAIgDAFQgFAFgHAAQgHAAgFgFgAjRB7QAAALAHAAQAHAAAAgLQAAgMgHAAQgHAAAAAMgAHKCMIAAgJIAJAAIAAAJgAGNCMIAAgjIAIAAIAAAGQADgGAGgBIAAAJIgBAAQgCAAgDADIgDADIAAAVgAFXCMIAAgXQABgGgFAAQgFAAgCAEIAAAZIgJAAIAAgxIAJAAIAAASQAFgFAEAAQALAAAAAMIAAAYgAEsCMIgFgWIgGAWIgIAAIgJgjIAIAAIAGAWIAEgWIAIAAIAGAWIAEgWIAIAAIgJAjgADiCMIAAgXQAAgGgEAAQgFAAgDAEIAAAZIgIAAIAAgjIAHAAIAAAEQAIgFADAAQAKAAAAAMIAAAYgAgZCMIAAgjIAIAAIAAAGQADgGAHgBIAAAJIgBAAQgDAAgDADIgDADIAAAVgAhPCMIAAgXQAAgGgEAAQgEAAgDAEIAAAZIgJAAIAAgxIAJAAIAAASQAFgFAFAAQAKAAAAAMIAAAYgAiMCMIAAgYQAAgFgEAAQgDAAgFAEIAAAZIgIAAIAAgYQAAgFgDAAQgEAAgEAEIAAAZIgIAAIAAgjIAIAAIAAAEQAEgFAGAAQAHAAACAFQAFgFAHAAQAIAAAAALIAAAZgAjvCMIAAgjIAHAAIAAAGQAEgGAGgBIAAAJIgBAAQgDAAgDADIgCADIAAAVgAkVCMIAAgxIAgAAIAAAIIgXAAIAAAMIARAAIAAAIIgRAAIAAAVgAIIBtIAAgVIgBAAIgGAVIgEAAIgGgVIAAAVIgEAAIAAgaIAHAAIAFASIABAAIAEgSIAHAAIAAAagAHjBtIAAgWIgHAAIAAgEIASAAIAAAEIgHAAIAAAWgAIuAuQgFgGAAgKIAAgqQAAgJAFgGQAGgHALAAQAKAAAGAHQAGAHgBAKIAAAFIgNAAQAAgJgCgEQgDgDgEAAQgGAAgBAJIAAAqQAAAJAIAAQAHAAABgMIAAgIIgKAAIAAgMIAYAAIAAArIgHAAIgDgGQgHAIgHAAQgJAAgGgGgAFbAtQgGgGAAgJIAAgqQAAgJAGgGQAGgHAKAAQAMAAAFAHQAGAGAAAJIAAAqQAAAJgGAGQgFAHgMAAQgKAAgGgHgAFkgMIAAApQAAAKAHAAQAIAAAAgKIAAgpQAAgJgIAAQgHAAAAAJgAEeAtQgGgGAAgJIAAgqQAAgJAGgGQAFgHAMAAQAKAAAFAHQAGAGAAALIAAAGIgPAAIAAgHQAAgKgGAAQgJAAABAJIAAApQgBAKAJAAQAGAAAAgJIAAgKIAPAAIAAAKQAAAJgGAGQgFAHgKAAQgMAAgFgHgAAAAuQgGgGgBgLIAAg9IANAAIAAA+QAAAJAIAAQAIAAgBgJIAAg+IAPAAIAAA9QABALgHAGQgFAGgLAAQgKAAgEgGgAjTAtQgFgGAAgJIAAgqQAAgJAFgGQAHgHAKAAQAMAAAFAHQAGAGAAAJIAAAqQAAAJgGAGQgFAHgMAAQgKAAgHgHgAjKgMIAAApQABAKAHAAQAIAAAAgKIAAgpQAAgJgIAAQgHAAgBAJgAkPAtQgGgGAAgJIAAgqQAAgJAGgGQAFgHAMAAQAKAAAGAHQAFAHAAAKIAAAGIgPAAIAAgHQAAgKgGAAQgIAAAAAJIAAApQAAAKAIAAQAGAAAAgJIAAgKIAPAAIAAAKQAAAJgFAGQgGAHgKAAQgMAAgFgHgAJmAyIAAhSIAnAAIAAAMIgYAAIAAAUIASAAIAAANIgSAAIAAAZIAaAAIAAAMgAHyAyIAAhSIAoAAIAAAMIgZAAIAAAUIATAAIAAANIgTAAIAAAZIAaAAIAAAMgAHCAyIAAhSIAPAAIAABGIAWAAIAAAMgAGSAyIAAhSIAOAAIAABGIAXAAIAAAMgADRAyIAAgjIgSgvIAPAAIAKAgIAAAAIAKggIAPAAIgRAvIAAAjgACeAyIAAhGIgPAAIAAgMIArAAIAAAMIgOAAIAABGgAB0AyIAAhSIAPAAIAABSgABUAyIgSgzIAAAzIgNAAIAAhSIANAAIASAuIAAAAIAAguIAOAAIAABSgAgjAyIAAhAIgNBAIgHAAIgOhAIAABAIgMAAIAAhSIATAAIAKAvIAAAAIAKgvIAUAAIAABSgAhtAyIAAhAIgOBAIgHAAIgNhAIAAAAIAABAIgMAAIAAhSIATAAIAKAvIAKgvIAUAAIAABSgADAg5IgLgjIgHAAIAAAjIgOAAIAAhVIAUAAQAMAAAGAGQAHAGAAANQgBARgJAFIAMAmgACuhoIAFAAQAGAAADgDQACgDAAgHQAAgHgCgDQgDgDgGAAIgFAAgABpg5IAAhVIAnAAIAAANIgZAAIAAAWIATAAIAAAMIgTAAIAAAZIAaAAIAAANgABBg5IAAhIIgOAAIAAgNIArAAIAAANIgOAAIAABIgAAgg5IgDgTIgPAAIgEATIgLAAIANhVIASAAIAQBVgAAQhZIALAAIgGgkIAAAAgAgjg5IgKg4IgKA4IgNAAIgPhVIANAAIAJA2IAAAAIAKg2IALAAIALA2IAAAAIAIg2IANAAIgPBVgAiDg5IAAhVIAnAAIAAANIgYAAIAAAWIASAAIAAAMIgSAAIAAAZIAaAAIAAANgAjAg5IAAhVIAWAAQAXAAgBAaIAAAhQABAagXAAgAiyhFIAGAAQAFAAADgDQACgCAAgHIAAglQAAgHgCgCQgDgDgFAAIgGAAgAjhg5IAAhVIAOAAIAABVgAkLg5IAAhIIgOAAIAAgNIArAAIAAANIgOAAIAABIgAp9hIQAWgqAogZQApgaAxAAQAzAAAqAcQgoANgiASQgWAMgJAIQhHAQgqAAQgPAAgMgCg");
	this.shape.setTransform(81.3,-56.6,1.292,1.292);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2C4F67").s().p("AgFCgIAAk/IALAAIAAE/g");
	this.shape_1.setTransform(-391.9,131.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2C4F67").s().p("AgYAUIAPgDQABATAIAAQAEAAACgDQACgCAAgEQAAgEgCgEQgBgDgCgCIgDgFIgNgKQgGgEgDgGQgCgFAAgIQAAgLAGgHQAHgGALAAQAEAAAFABQAEACACACIAFAGIACAHIABAIIgOADIgBgFIgBgEIgCgEIgCgCIgDgBQgEABgBACQgCACAAAEQAAAFACADQABADAEADIALALIAFAEIAFAGQACAEABAEIABAJQAAAKgGAHQgIAGgKAAQgYAAgBgdg");
	this.shape_2.setTransform(135.1,-16.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2C4F67").s().p("AgIAwQgFgCgEgDQgDgCgBgFIgEgIIgBgLIAAggIABgLIAEgJQABgFADgCQAEgDAFgBQAEgCAEAAQAIAAAFACQAFACADAEQADADABAFQACAFgBAHIAAAIIgRAAIAAgIIAAgKQgBgFgHAAIgBAAIgBABIgDABIgCADIgBADIgBAEIAAAEIAAAnQABAJACAEQACADADAAIAEAAIACgBIACgCIABgDIAAgDIAAgDIAAgEIAAgIIARAAIAAAIIAAAKIgCAIQgDAEgDACQgDADgEABIgLABQgEAAgEgBg");
	this.shape_3.setTransform(128.8,-16.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2C4F67").s().p("AgHAwIAAhfIAPAAIAABfg");
	this.shape_4.setTransform(123.9,-16.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2C4F67").s().p("AANAwIgWg4IAAA4IgPAAIAAhfIAMAAIAWA1IAAg1IAPAAIAABfg");
	this.shape_5.setTransform(119,-16.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2C4F67").s().p("AgUApQgGgIgBgQIAAghQABgIABgGQABgGAEgEQADgEAGgCQAFgCAGAAQAPAAAGAIQAHAIgBAQIAAAhQAAAIgBAGQgBAGgDAEQgEAEgFACQgFACgIAAQgNAAgHgIgAgDgiIgEADIgBAFIgBAFIAAArIABAEIAAAEIADAEIADACIACAAIAEAAIADgCIABgEIABgEIAAgEIAAgrIAAgFIgBgFIgDgDIgFgBIgDABg");
	this.shape_6.setTransform(112.4,-16.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2C4F67").s().p("AAJAwIgJgsIgIAAIAAAsIgSAAIAAhfIAWAAIALABQAGABAEAEQAEADACAEQACAGAAAHQAAAJgDAFQgCAHgHAAIAOAwgAgIgFIAEAAQAGAAADgEQADgEAAgHQAAgIgCgDQgDgEgGAAIgFAAg");
	this.shape_7.setTransform(105.8,-16.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2C4F67").s().p("AgHAwIAAhSIgQAAIAAgNIAvAAIAAANIgPAAIAABSg");
	this.shape_8.setTransform(99.8,-16.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2C4F67").s().p("AAMAwIgEgXIgOAAIgFAXIgRAAIAVhfIAQAAIAUBfgAgFAOIALAAIgGgmg");
	this.shape_9.setTransform(94.2,-16.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2C4F67").s().p("AAJAwIAAgsIgSAAIAAAsIgRAAIAAhfIARAAIAAAoIASAAIAAgoIASAAIAABfg");
	this.shape_10.setTransform(87.6,-16.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2C4F67").s().p("AgIAwQgGgCgCgDQgEgCgCgFIgDgIIAAgLIAAggIAAgLIADgJQACgFAEgCQACgDAGgBQAEgCAEAAQAHAAAGACQAFACADAEQADADABAFQABAFABAHIAAAIIgRAAIAAgIIgBgKQgBgFgHAAIgBAAIgBABIgDABIgCADIgBADIAAAEIAAAEIAAAnQgBAJADAEQACADADAAIADAAIADgBIACgCIABgDIABgDIAAgDIAAgEIAAgIIARAAIAAAIIgBAKIgCAIQgDAEgDACQgCADgFABIgLABQgEAAgEgBg");
	this.shape_11.setTransform(80.9,-16.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2C4F67").s().p("AgTAwIAAhfIAnAAIAAAMIgVAAIAAAcIAQAAIAAALIgQAAIAAAgIAVAAIAAAMg");
	this.shape_12.setTransform(75.3,-16.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2C4F67").s().p("AAUAwIgBhBIgPBBIgIAAIgOhBIgBBBIgNAAIABhfIASAAIANBCIAOhCIARAAIACBfg");
	this.shape_13.setTransform(68.5,-16.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2C4F67").s().p("AgSAwIAahfIALAAIgaBfg");
	this.shape_14.setTransform(62,-16.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2C4F67").s().p("AgKAvQgEgCgDgCQgEgDgBgEQgCgFgBgEIgBgMIAAg/IARAAIAABBIABAFIAAAFIACAEIADAEIADABIAEgBIADgEIACgEIABgFIAAgFIAAhBIARAAIAAA/IgBAMIgCAJIgFAHQgDACgFACQgFABgGAAQgFAAgFgBg");
	this.shape_15.setTransform(56.2,-16.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#2C4F67").s().p("AgZAwIAAhfIAXAAQAGAAAGABQAGACADAEQAEAEACAGQABAFAAAIIAAAhQAAAIgBAHQgCAFgEAEQgDAEgGACQgFACgHAAgAgIAjIAGAAIACAAIAEgBIACgCIABgDIABgEIAAgEIAAgFIAAgiIAAgFIgBgFIgBgCIgCgCIgEgCIgCgBIgGAAg");
	this.shape_16.setTransform(49.6,-16.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2C4F67").s().p("AgTAwIAAhfIAnAAIAAAMIgVAAIAAAcIAQAAIAAALIgQAAIAAAgIAVAAIAAAMg");
	this.shape_17.setTransform(43.9,-16.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#2C4F67").s().p("AgHAHIAAgOIAOAAIAAAOg");
	this.shape_18.setTransform(39.9,-12.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2C4F67").s().p("AgIAwQgGgCgCgDQgEgCgCgFIgCgIIgBgLIAAggIABgLIACgJQACgFAEgCQACgDAGgBQAEgCAFAAQAGAAAGACQAFACADAEQADADABAFQABAFABAHIAAAIIgRAAIAAgIIgBgKQgCgFgGAAIAAAAIgDABIgCABIgCADIgBADIAAAEIAAAEIAAAnQgBAJADAEQACADAEAAIACAAIADgBIACgCIABgDIABgDIAAgDIAAgEIAAgIIARAAIAAAIIgBAKIgDAIQgCAEgCACQgDADgFABIgKABQgFAAgEgBg");
	this.shape_19.setTransform(35.4,-16.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#2C4F67").s().p("AgJAwQgEgCgEgDQgDgCgBgFIgEgIIgBgLIAAggIABgLIAEgJQABgFADgCQAEgDAEgBQAFgCAEAAQAIAAAFACQAFACADAEQADADABAFQACAFgBAHIAAAIIgRAAIAAgIIAAgKQgBgFgHAAIgBAAIgBABIgDABIgCADIgBADIgBAEIAAAEIAAAnQABAJACAEQACADADAAIAEAAIACgBIACgCIABgDIAAgDIAAgDIAAgEIAAgIIARAAIAAAIIAAAKIgCAIQgDAEgDACQgDADgEABIgLABQgEAAgFgBg");
	this.shape_20.setTransform(28.9,-16.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#2C4F67").s().p("AgHAwIAAhSIgQAAIAAgNIAvAAIAAANIgPAAIAABSg");
	this.shape_21.setTransform(23.1,-16.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Layer 1
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#91D2E5").s().p("AwGHFIAAuJMAgMAAAIAAOJg");
	this.shape_22.setTransform(82.3,-47.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_22).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-392.5,-93.1,577.9,241);


(lib.newFrame = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(332.2,-84.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgjBEQgJgOgBgbIAAgzQAAgOADgLQACgKAFgHQAFgIAJgEQAJgDAMAAQAXAAALAMQALAMgBAXIAAAIIgcAAIAAgIIAAgJIgBgHQgBgDgCgDIgFgDIgHgBIgEABIgFACIgCAEIgCAEIgBAGIAAAFIAAAHIAAA/QgBAPAEAHQAEAHAIAAQAFgBAEgCQADgCACgDIADgJIABgOIAAgMIgRAAIAAgSIAsAAIAABRIgUAAIgCgRQgHATgTgBQgXAAgKgOg");
	this.shape_1.setTransform(324.4,-91.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAWBRIgmhfIAABfIgZAAIAAigIAVAAIAlBZIAAhZIAZAAIAACgg");
	this.shape_2.setTransform(313.4,-91.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNBRIAAigIAbAAIAACgg");
	this.shape_3.setTransform(305.3,-91.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQBRIgShKIgNAAIAABKIgdAAIAAigIAlAAQALAAAJABQAJADAHAFQAHAFADAIQADAIAAANQAAAPgEAJQgFALgKACIAWBQgAgPgLIAHAAQAMABAFgGQAGgFAAgOQAAgNgFgFQgFgGgLAAIgJAAg");
	this.shape_4.setTransform(297.2,-91.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSBPQgIgCgEgFQgFgFgEgHQgDgHgBgIIgBgUIAAhpIAdAAIAABsIAAAKIABAIQABAEACADQACADADABQADACADABQAEgBADgCQADgBACgDIADgHIABgIIAAgKIAAhsIAdAAIAABpQAAALgCAJQgBAIgDAHQgCAHgGAFQgFAFgIACQgIACgKAAQgJAAgJgCg");
	this.shape_5.setTransform(285.8,-91);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBRIAAiLIgbAAIAAgVIBRAAIAAAVIgaAAIAACLg");
	this.shape_6.setTransform(275.9,-91.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgQBQQgIgDgFgEQgFgFgDgHQgEgHgBgIQgBgIgBgKIAAg2QABgLABgIQABgIAEgHQADgHAFgEQAFgFAIgCQAIgDAIAAQANAAAIADQAJADAFAGQAFAGACAJQACAJAAALIAAANIgcAAIAAgNQAAgNgBgEQgDgIgKgBIgCAAIgEABIgEADIgDAEIgCAGIgBAGIAAAHIAABDQAAAOAEAHQADAFAHABIAGgBIAEgCIADgDIACgEIABgFIAAgGIAAgGIAAgOIAcAAIAAANQAAAJgBAHQgBAIgDAGQgDAHgGADQgEAEgIADQgHACgLAAQgIAAgIgCg");
	this.shape_7.setTransform(266.4,-91.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAVBRIgHgmIgaAAIgHAmIgcAAIAhigIAdAAIAhCggAgJAXIAUAAIgLhAg");
	this.shape_8.setTransform(255.7,-91.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggBRIAAigIBBAAIAAAUIgjAAIAAAvIAbAAIAAATIgbAAIAABKg");
	this.shape_9.setTransform(246.9,-91.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSBPQgIgCgEgFQgFgFgEgHQgDgHgBgIIgBgUIAAhpIAdAAIAABsIAAAKIABAIQABAEACADQACADADABQADACADABQAEgBADgCQADgBACgDIADgHIABgIIAAgKIAAhsIAdAAIAABpQAAALgCAJQgBAIgCAHQgDAHgGAFQgFAFgIACQgIACgKAAQgJAAgJgCg");
	this.shape_10.setTransform(236.8,-91);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAWBRIgmhfIAABfIgZAAIAAigIAVAAIAlBZIAAhZIAZAAIAACgg");
	this.shape_11.setTransform(225.7,-91.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAVBRIgHgmIgaAAIgHAmIgcAAIAhigIAdAAIAhCggAgJAXIAUAAIgLhAg");
	this.shape_12.setTransform(215,-91.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAiBRIgChuIgYBuIgPAAIgYhvIgBBvIgXAAIADigIAeAAIAWBvIAYhvIAdAAIADCgg");
	this.shape_13.setTransform(203,-91.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgrBRIAAigIAmAAQAMAAALACQAJADAGAHQAGAGACAKQADAJAAANIAAA5QAAANgDAKQgCAKgGAGQgGAHgJADQgKAEgMAAgAgNA8IAIAAIAGgBIAFgCIAEgDIACgFIABgGIABgHIAAgJIAAg5IAAgKIgBgHIgCgFIgEgEIgGgCIgGgBIgIAAg");
	this.shape_14.setTransform(185.9,-91.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghBRIAAigIBCAAIAAAUIgkAAIAAAvIAcAAIAAATIgcAAIAAA1IAlAAIAAAVg");
	this.shape_15.setTransform(176.3,-91.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQBQQgIgDgFgEQgFgFgDgHQgEgHgBgIQgCgIABgKIAAg2QgBgLACgIQABgIAEgHQADgHAFgEQAFgFAIgCQAIgDAIAAQANAAAIADQAJADAFAGQAFAGACAJQACAJABALIAAANIgdAAIAAgNQAAgNgBgEQgDgIgKgBIgCAAIgEABIgEADIgDAEIgCAGIgBAGIAAAHIAABDQABAOADAHQADAFAHABIAGgBIAEgCIADgDIACgEIABgFIAAgGIAAgGIAAgOIAdAAIAAANQgBAJgBAHQgBAIgDAGQgDAHgGADQgEAEgIADQgHACgLAAQgIAAgIgCg");
	this.shape_16.setTransform(166.4,-91.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAWBRIgmhfIAABfIgZAAIAAigIAVAAIAlBZIAAhZIAZAAIAACgg");
	this.shape_17.setTransform(155.5,-91.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAVBRIgHgmIgaAAIgHAmIgcAAIAhigIAdAAIAhCggAgJAXIAUAAIgLhAg");
	this.shape_18.setTransform(144.9,-91.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgNBRIghigIAbAAIATBuIAUhuIAbAAIghCgg");
	this.shape_19.setTransform(134.5,-91.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgrBRIAAigIAmAAQAMAAAKACQAKADAGAHQAGAGADAKQACAJAAANIAAA5QAAANgCAKQgDAKgGAGQgFAHgLADQgJAEgMAAgAgNA8IAIAAIAFgBIAHgCIADgDIADgFIABgGIAAgHIAAgJIAAg5IAAgKIgBgHIgCgFIgEgEIgGgCIgHgBIgHAAg");
	this.shape_20.setTransform(124,-91.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAVBRIgHgmIgaAAIgHAmIgcAAIAhigIAdAAIAhCggAgJAXIAUAAIgLhAg");
	this.shape_21.setTransform(113.1,-91.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAUBIIgihUIAABUIgXAAIAAiPIASAAIAiBQIAAhQIAXAAIAACPg");
	this.shape_22.setTransform(273.8,-112.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgMBIIAAiPIAZAAIAACPg");
	this.shape_23.setTransform(266.4,-112.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AglAeIAXgFQABAdAOAAQAGAAADgEQADgEAAgGQAAgGgDgFQgCgFgCgDIgHgIIgTgPQgIgHgFgIQgDgIAAgMQgBgRALgKQAKgJAQAAQAGAAAHACQAGACAEADQAEAEADAFQADAFABAGIABAMIgWAFIgBgIIgBgHIgDgFIgDgDIgFgBQgGAAgCAEQgEADAAAGQAAAHADAFQADAEAGAGIARAQIAIAGIAHAKQADAFABAGQACAGAAAHQAAAQgKAKQgKAKgRAAQgkAAgCgsg");
	this.shape_24.setTransform(255.2,-112.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_25.setTransform(245.9,-112.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape_26.setTransform(237.1,-112.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape_27.setTransform(229.4,-112.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_28.setTransform(220.5,-112.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AASBIIgGgiIgXAAIgGAiIgZAAIAeiPIAZAAIAeCPgAgIAVIARAAIgJg6g");
	this.shape_29.setTransform(210.6,-112.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgOBIQgHgDgFgEQgEgEgDgGQgEgHgBgHQgBgHAAgJIAAgxQAAgJABgIQABgHAEgGQADgGAEgFQAFgEAHgCQAHgCAIAAQAKAAAIADQAIADAFAFQAEAGACAHQACAIAAAKIAAAMIgaAAIAAgMQABgLgCgEQgCgHgJgBIgBAAIgEABIgFADIgCADIgBAFIgBAGIAAAHIAAA8QAAAMADAGQADAFAHAAIAEAAIAEgCIADgDIABgDIABgFIAAgFIAAgFIAAgNIAaAAIAAAMQAAAIgBAGQgBAHgDAFQgDAGgEAEQgFAEgHACQgHACgIAAQgIAAgHgCg");
	this.shape_30.setTransform(201.1,-112.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgMBIIAAh8IgYAAIAAgTIBJAAIAAATIgYAAIAAB8g");
	this.shape_31.setTransform(188,-112.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgfA+QgJgMgBgYIAAg0QAAgLADgJQACgIAFgHQAFgGAIgDQAIgDAKAAQAWAAAKAMQAKAMAAAXIAAA0QAAALgDAJQgCAJgFAGQgFAHgIADQgIADgLAAQgVAAgKgMgAgHg0QgDACgBADIgCAGIgBAJIAABAIABAHIABAGIADAFQABACADABIAFABIAGgBQADgBABgCIADgFIACgGIAAgHIAAhAIgBgJIgCgGQgBgDgDgCQgEgCgEAAQgDAAgEACg");
	this.shape_32.setTransform(179.1,-112.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAPBIIAAhCIgdAAIAABCIgaAAIAAiPIAaAAIAAA8IAdAAIAAg8IAaAAIAACPg");
	this.shape_33.setTransform(168.9,-112.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(105.8,-126.5,230.6,52.5);


(lib.mechanics = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAWQAIgCAFgGQADgGAAgIIgSAAIAAgjIAjAAIAAAhQAAAggdAGg");
	this.shape.setTransform(341.2,9.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_1.setTransform(330.5,-1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBsQgKgEgHgGQgIgGgEgKQgEgJgCgLQgCgLAAgNIAAhKQAAgOACgLQACgMAEgJQAEgJAIgGQAHgGAKgEQALgDAMAAQAQAAAMAEQALAEAIAJQAGAIADAMQADALAAAPIAAATIgmAAIAAgTQgBgQgBgGQgDgLgNgBIgDAAIgGABQgEABgDADIgDAFIgDAIIgBAJIAAAKIAABaQAAAUAFAIQAFAIAKAAIAHgBIAGgDIAEgEIACgFIABgHIABgHIAAgJIAAgTIAmAAIAAASQAAAMgCAKQgBAJgFAJQgEAJgGAFQgHAGgKADQgLADgNAAQgMAAgLgDg");
	this.shape_2.setTransform(315.4,-1.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsBtIAAjZIBZAAIAAAcIgyAAIAAA/IAnAAIAAAaIgnAAIAABIIAzAAIAAAcg");
	this.shape_3.setTransform(302.8,-1.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSBtIAAi7IglAAIAAgeIBuAAIAAAeIgjAAIAAC7g");
	this.shape_4.setTransform(290.9,-1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfAMIAAgXIA/AAIAAAXg");
	this.shape_5.setTransform(280.4,0.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_6.setTransform(267.8,-1.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgvBcQgOgUAAgkIAAhFQABgUADgNQACgNAHgLQAHgLANgEQAMgGAQAAQAgABAOAPQAOAQAAAgIAAALIgmAAIAAgLIAAgMIgCgJQgBgFgDgDQgCgCgEgBQgEgCgGAAIgGABIgGADIgEAEIgDAGIgBAIIAAAIIAAAJIAABWQAAATAEAKQAGAIALABQAHgBAFgCQAFgDADgFIADgNIABgRIAAgSIgXAAIAAgYIA7AAIAABuIgaAAIgCgXQgLAZgYAAQgfABgOgUg");
	this.shape_7.setTransform(252.3,-1.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSBtIAAjZIAlAAIAADZg");
	this.shape_8.setTransform(241.1,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_9.setTransform(229.5,-1.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(219.8,-22,126.1,40.3);


(lib.jobs = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQASIAAgjIAiAAIAAAjg");
	this.shape.setTransform(330.5,-26.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag4AtIAjgIQABAsAVAAQAKAAAEgGQAEgFAAgKQAAgJgDgHQgEgIgEgFIgKgMIgdgXQgMgLgHgLQgGgMAAgSQAAgaAPgOQAPgOAaAAQAKAAAJADQAKADAFAFQAGAFAEAIQAEAIADAIIACATIgiAGIgBgLIgCgKQgBgFgCgDQgDgDgDgCQgEgCgDABQgKAAgEAGQgEAFAAAJQAAAKADAHQAFAHAJAIIAaAYIAMALIAKAOQAFAIACAJQADAJAAALQAAAYgPAOQgPAPgZAAQg4AAgChCg");
	this.shape_1.setTransform(321,-35.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag8BtIAAjZIA1AAQANAAAMADQAKADAKAGQAIAGAEALQAFALAAAQQAAAoggAFQATAEAKALQAKANgBAYQAAAfgPARQgQAQgeAAgAgVBRIAPAAQAQAAAGgJQAIgIgBgTQABgUgJgJQgHgJgRAAIgMAAgAgVgTIAMAAQAQAAAGgHQAIgIAAgSQgBgJgCgFQgCgGgFgDQgFgDgGgBIgPgBIgGAAg");
	this.shape_2.setTransform(307,-35.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgvBdQgPgSAAgkIAAhOQABgSADgMQADgNAHgKQAIgJAMgFQAMgEAQAAQAhAAAPASQAOASAAAjIAABOQAAASgDANQgEANgGAJQgIAKgMAFQgMAEgRAAQggAAgPgSgAgLhPQgEADgDAEIgCAKIgBANIAABiIABAKIABAJQACAFACADQACACAEACQAFACAEAAQAFAAAEgCQAEgCADgCIAEgIIACgJIAAgKIAAhiIgBgNQgBgFgCgFQgCgEgFgDQgEgCgHAAQgGAAgFACg");
	this.shape_3.setTransform(291.6,-35.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghBvIAAgcQASAAAFgFQAGgGAAgQIAAimIAmAAIAACnQAAAOgCAKQgDAKgGAGQgFAIgKADQgIADgOAAg");
	this.shape_4.setTransform(278.9,-35.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag6BtIAAjZIAyAAQASAAANAEQAOAEAHAJQAJAIADANQADAMAAASIAABNQAAATgDANQgEANgHAJQgIAJgNAFQgNAEgRAAgAgTBRIALAAIAJgBIAHgDQAEgBACgEIACgGIACgIIABgJIAAgMIAAhOIgBgNIgBgJQgBgFgCgDIgFgEQgDgDgEAAIgKgBIgLAAg");
	this.shape_5.setTransform(261.3,-35.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAeBtIg0iAIAACAIghAAIAAjZIAbAAIA0B6IAAh6IAhAAIAADZg");
	this.shape_6.setTransform(246.4,-35.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAbBtIgIgzIgkAAIgJAzIgmAAIAtjZIAnAAIAtDZgAgNAgIAbAAIgOhYg");
	this.shape_7.setTransform(232,-35.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAtBtIgCiVIgfCVIgWAAIggiVIgCCVIgeAAIADjZIApAAIAeCYIAgiYIAoAAIAEDZg");
	this.shape_8.setTransform(215.8,-35.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgtBtIAAjZIBaAAIAAAcIgyAAIAAA/IAnAAIAAAaIgnAAIAABIIAyAAIAAAcg");
	this.shape_9.setTransform(201.3,-35.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag6BtIAAjZIAyAAQASAAANAEQANAEAJAJQAHAIAEANQAEAMgBASIAABNQABATgEANQgDANgIAJQgIAJgNAFQgNAEgRAAgAgTBRIAMAAIAIgBIAIgDQADgBABgEIADgGIACgIIABgJIAAgMIAAhOIAAgNIgBgJQgCgFgCgDIgEgEQgEgDgEAAIgKgBIgLAAg");
	this.shape_10.setTransform(187.7,-35.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfAMIAAgXIA/AAIAAAXg");
	this.shape_11.setTransform(175.3,-33.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_12.setTransform(162.7,-35.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBcQgNgTAAgmIAAhFQAAgTADgNQACgOAHgKQAHgKAMgGQAMgEARAAQAggBAOARQAOAPAAAgIAAALIgmAAIAAgLIAAgMIgCgJQgBgFgDgCQgCgDgEgCQgEgBgGAAIgGABIgGADIgEAEIgDAHIgBAHIAAAHIgBAJIAABWQAAAVAGAIQAEAJAMAAQAHAAAFgCQAFgDADgFIADgMIABgSIAAgSIgXAAIAAgYIA7AAIAABtIgZAAIgEgWQgKAagZAAQgeAAgOgUg");
	this.shape_13.setTransform(147.2,-35.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgSBtIAAjZIAlAAIAADZg");
	this.shape_14.setTransform(136,-35.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_15.setTransform(124.4,-35.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(114.7,-56,220.4,40.3);


(lib.image = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._300x250();
	this.instance.setTransform(0.2,-44,0.752,0.752);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.2,-44,225.6,188);


(lib._if = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAWQAIgCAFgGQADgGAAgIIgSAAIAAgjIAjAAIAAAhQAAAggdAGg");
	this.shape.setTransform(414.6,16);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvBcQgNgUAAgkIAAhFQAAgUADgNQACgNAHgLQAHgLAMgEQAMgGARAAQAgABAOAQQAOAPAAAgIAAALIgmAAIAAgLIAAgMIgCgJQgBgFgDgDQgCgCgEgBQgEgCgGAAIgGABIgGADIgEAEIgDAGIgBAIIAAAIIgBAJIAABVQAAAVAGAJQAEAIAMABQAHAAAFgDQAFgDADgFIADgNIABgRIAAgSIgXAAIAAgYIA7AAIAABuIgZAAIgEgXQgKAZgZAAQgeABgOgUg");
	this.shape_1.setTransform(404.2,5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAeBtIg0iAIAACAIghAAIAAjZIAbAAIA0B6IAAh6IAgAAIAADZg");
	this.shape_2.setTransform(389.4,5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSBtIAAjZIAlAAIAADZg");
	this.shape_3.setTransform(378.3,5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSBtIAAhTIgsiGIAlAAIAZBXIAahXIAlAAIgtCGIAABTg");
	this.shape_4.setTransform(368,5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBtIgIgzIgkAAIgJAzIgmAAIAtjZIAnAAIAtDZgAgNAgIAbAAIgOhYg");
	this.shape_5.setTransform(354.4,5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag6BtIAAjZIA9AAQA4AAAAA+QAAAfgPAOQgQAMgcAAIgSAAIAABigAgSgPIANAAQAPAAAGgGQAFgHAAgSIAAgQQgBgFgDgFQgDgEgGgCQgFgCgIAAIgNAAg");
	this.shape_6.setTransform(340.9,5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfAMIAAgXIA/AAIAAAXg");
	this.shape_7.setTransform(328.6,7.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_8.setTransform(315.9,5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgvBcQgOgUAAgkIAAhFQABgUADgNQACgNAHgLQAHgLAMgEQANgGAQAAQAgABAOAQQAOAPAAAgIAAALIgmAAIAAgLIAAgMIgCgJQgBgFgDgDQgCgCgEgBQgEgCgGAAIgGABIgGADIgEAEIgDAGIAAAIIgBAIIAAAJIAABVQAAAVAEAJQAGAIALABQAHAAAFgDQAFgDADgFIADgNIABgRIAAgSIgXAAIAAgYIA7AAIAABuIgaAAIgCgXQgLAZgYAAQgfABgOgUg");
	this.shape_9.setTransform(300.5,5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSBtIAAjZIAlAAIAADZg");
	this.shape_10.setTransform(289.3,5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAWBtIAAhjIgrAAIAABjIgoAAIAAjZIAoAAIAABcIArAAIAAhcIAoAAIAADZg");
	this.shape_11.setTransform(277.7,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(268,-15.3,151.3,40.3);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape.setTransform(261.5,-56.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_1.setTransform(252.6,-56.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA+QgKgMAAgYIAAg0QAAgLACgJQACgIAFgHQAEgGAJgDQAIgDAKAAQAWAAAKAMQAKAMAAAXIAAA0QAAALgCAJQgDAJgFAGQgEAHgJADQgIADgLAAQgVAAgJgMgAgHg0QgDACgBADIgCAGIAAAJIAABAIAAAHIABAGIACAFQACACADABIAFABIAGgBQADgBABgCIADgFIACgGIAAgHIAAhAIgBgJIgCgGQgCgDgDgCQgCgCgFAAQgDAAgEACg");
	this.shape_2.setTransform(242.3,-56.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAeBIIgBhiIgVBiIgOAAIgVhiIgCBiIgUAAIACiPIAcAAIATBkIAVhkIAbAAIACCPg");
	this.shape_3.setTransform(231.1,-56.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAUBIIgihUIAABUIgXAAIAAiPIASAAIAiBQIAAhQIAXAAIAACPg");
	this.shape_4.setTransform(215.7,-56.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_5.setTransform(206,-56.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASBIIgGgiIgXAAIgGAiIgZAAIAeiPIAZAAIAeCPgAgIAVIARAAIgJg6g");
	this.shape_6.setTransform(196.1,-56.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape_7.setTransform(188,-56.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIAaAAIAAB9IAhAAIAAASg");
	this.shape_8.setTransform(180.4,-56.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// base
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#91D2E5").s().p("AqSClQgEAAgDgDQgDgDAAgEIAAk1QAAgEADgDQADgDAEAAIUlAAQAEAAADADQADADAAAEIAAE1QAAAEgDADQgDADgEAAgAqICRIURAAIAAkhI0RAAg");
	this.shape_9.setTransform(220.8,-56.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// hit
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(141,216,232,0)").s().p("AqSClQgEAAgDgDQgDgDAAgEIAAk1QAAgEADgDQADgDAEAAIUlAAQAEAAADADQADADAAAEIAAE1QAAAEgDADQgDADgEAAg");
	this.shape_10.setTransform(220.8,-51.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.8,-72.8,134,38.1);


// stage content:
(lib._728x90 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_297 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(297).call(this.frame_297).wait(1));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#1B1B1B").ss(1,1,1).p("EA4zAG9MhxlAAAIAAt5MBxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(298));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(150,132.9);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(283).to({y:100.9},0).to({y:79.7,alpha:1},11,cjs.Ease.get(1)).wait(4));

	// Layer 5
	this.instance_1 = new lib.Symbol17();
	this.instance_1.setTransform(635,101,1,1,0,0,0,93,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(298));

	// in 2 years
	this.instance_2 = new lib.twoyears();
	this.instance_2.setTransform(371.4,50.3,0.6,0.6);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(216).to({scaleX:1.05,scaleY:1.05,alpha:1},6).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(39).to({alpha:0},11).wait(22));

	// high demand
	this.instance_3 = new lib.jobs();
	this.instance_3.setTransform(134.4,104.9);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(117).to({x:148.4,alpha:1},22).wait(60).to({alpha:0},17,cjs.Ease.get(1)).wait(82));

	// high tech
	this.instance_4 = new lib.mechanics();
	this.instance_4.setTransform(141.2,59.5,1,1,0,0,0,62.1,14);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(95).to({x:148.2,alpha:1},22,cjs.Ease.get(1)).wait(82).to({alpha:0},17,cjs.Ease.get(1)).wait(82));

	// high paying'
	this.instance_5 = new lib._if();
	this.instance_5.setTransform(65.9,25.1,1,1,0,0,0,48.3,12);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(73).to({x:72.9,alpha:1},22,cjs.Ease.get(1)).wait(104).to({alpha:0},17,cjs.Ease.get(1)).wait(82));

	// Layer 10
	this.instance_6 = new lib.newFrame();
	this.instance_6.setTransform(149.7,167.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(265).to({_off:false},0).to({alpha:1},18,cjs.Ease.get(1)).wait(15));

	// images
	this.instance_7 = new lib.image();
	this.instance_7.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(6).to({alpha:1},19,cjs.Ease.get(1)).wait(273));

	// Layer 13
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2C4F67").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(298));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(345.7,-0.4,746.9,347.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;