// Generated by CoffeeScript 1.7.1
(function() {
  var AUTOCOLLAPSE_DELAY, TRANSITION_TIME,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TRANSITION_TIME = 200;

  AUTOCOLLAPSE_DELAY = 8000;

  if (window.DIAAdvertising == null) {
    window.DIAAdvertising = {};
  }

  DIAAdvertising.RMU = (function() {
    function RMU(opts) {
      this.opts = opts;
      this.rmu = $j("#" + this.opts.id);

    }


    return RMU;

  })();

  DIAAdvertising.Pushdown = (function(_super) {
    __extends(Pushdown, _super);

    function Pushdown(opts) {
      Pushdown.__super__.constructor.call(this, opts);
      this.pushdown = $j('.pushdown', this.rmu);
      this.pushdownContainer = $j('.rmu-container', this.rmu);
      this.initPushdown();
    }

    Pushdown.prototype.initPushdown = function() {
      $j('> div', this.rmu).css('backgroundImage', "url(" + this.opts.img + ")");
      return $j(window).load((function(_this) {
        return function() {
          //setTimeout(function() {
           // return _this.expand();
         // }, TRANSITION_TIME);
          //_this.timeout = setTimeout(function() {
           // return _this.collapse();
          //}, AUTOCOLLAPSE_DELAY);
          _this.pushdown.click(function() {
            _this.expand();
            return clearTimeout(_this.timeout);
          });

          $j('a', _this.rmu).click(function() {
            return clearTimeout(_this.timeout);
          });
		  $j('.rmu-overlink', _this.rmu).click(function() {
            return clearTimeout(_this.timeout);
          });
          return $j('.close', _this.rmu).click(function() {
            _this.collapse();
            clearTimeout(_this.timeout);
            return false;
          });
        };
      })(this));
    };

    Pushdown.prototype.expand = function() {
      this.rmu.addClass('expanded');
      this.pushdown.slideUp(TRANSITION_TIME);
      this.pushdownContainer.slideDown(TRANSITION_TIME);
	  var vid = document.getElementById("myVideo");
		vid.play();	  
      return false;
    };

    Pushdown.prototype.collapse = function() {
      this.rmu.removeClass('expanded');
      this.pushdownContainer.slideUp(TRANSITION_TIME);
      this.pushdown.slideDown(TRANSITION_TIME);
		
		var vid = document.getElementById("myVideo");
		vid.pause();

      return false;
    };

    return Pushdown;

  })(DIAAdvertising.RMU);

}).call(this);
