(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"_300x250.jpg", id:"_300x250"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._300x250 = function() {
	this.initialize(img._300x250);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.twoyears = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D9C993").s().p("AEtBYQgKgDgHgGQgIgGgFgKQgGgKgDgMIAhgHQABAHAEAGQACAGAEADQAHAHAIAAQAKAAAGgGQAFgFAAgKQAAgGgDgFQgDgFgFgEQgFgFgWgLIgNgGQgHgFgGgFQgFgHgDgHQgEgHAAgJQAAgLAEgKQAEgJAHgHQAGgGAKgDQAKgDANgBQAMABAIADQAKADAHAFQAGAGAEAJQAFAGADALIgeAIQgFgMgGgGQgGgFgIgBQgJAAgGAGQgEAEAAAKQgBAEAEAFQADAEAFADIAbAQIAOAIQAHAEAFAFQAFAHAEAIQACAIAAAKQAAAMgDAJQgFAKgGAGQgIAHgKADQgLAEgNgBQgLABgIgDgACkBYQgJgDgHgGQgIgGgGgKQgFgKgEgMIAigHQABAHADAGQADAGADADQAIAHAIAAQAKAAAFgGQAGgFAAgKQAAgGgDgFQgDgFgFgEQgFgFgWgLIgNgGQgIgFgFgFQgGgHgDgHQgDgHAAgJQAAgLADgKQAEgJAHgHQAGgGAKgDQAKgDAOgBQAKABAKADQAJADAHAFQAHAGAEAJQAFAGACALIgeAIQgEgMgHgGQgFgFgJgBQgJAAgFAGQgFAEAAAKQAAAEADAFQADAEAGADIAaAQIAOAIQAHAEAFAFQAGAHADAIQADAIAAAKQAAAMgEAJQgEAKgHAGQgIAHgKADQgKAEgNgBQgLABgJgDgAmZBYQgLgEgGgGQgJgIgDgLQgEgMAAgPIAAg+QAAgQAEgMQADgLAJgIQAGgGALgEQALgDAMAAQANAAAKADQAKAEAIAGQAHAIAEALQAEAMAAAQIAAA+QAAAPgEAMQgEALgHAIQgIAGgKAEQgKACgNAAQgMAAgLgCgAmSg2QgDACgCAGQgBAEAAAHIAABGQAAAIABAFQACAFADADQAFAEALABQALgBAFgEQADgDACgFQABgFAAgIIAAhGQAAgHgBgEQgCgGgDgCQgFgGgLAAQgLAAgFAGgAGYBZIAAgkIAjAAIAAAkgAAKBZIAAiwIBdAAIAAAeIg8AAIAAAoIAtAAIAAAcIgtAAIAAAwIA+AAIAAAegAhhBZIAAiwIAiAAIAACSIA2AAIAAAegAjfBZIgehJIgQAAIAABJIghAAIAAiwIAwAAQAQAAALAEQALADAIAHQAHAHAEAKQAEAJAAANQAAAIgBAIIgGAMQgDAGgFACQgFAFgHACIAhBQgAkNgKIASAAQAMAAAFgGQADgDACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgFgGgMAAIgSAAg");
	this.shape.setTransform(-2,24.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D9C993").s().p("AKMBYQgJgDgHgGQgHgGgGgKQgGgKgDgMIAhgHQACAHADAGQACAGAFADQAGAHAIAAQAKAAAFgGQAGgFABgKQAAgGgEgFQgDgFgFgEQgFgFgWgLIgNgGQgHgFgFgFQgGgHgCgHQgEgHAAgJQAAgLAEgKQADgJAHgHQAGgGAKgDQAKgDANgBQAMABAIADQAKADAHAFQAGAGAFAJQAFAGACALIgeAIQgFgMgGgGQgFgFgKgBQgJAAgEAGQgGAEAAAKQABAEADAFQADAEAFADIAbAQIAOAIQAHAEAEAFQAHAHACAIQADAIAAAKQAAAMgDAJQgFAKgGAGQgIAHgKADQgLAEgNgBQgKABgKgDgAhVBYQgKgEgHgGQgJgIgDgLQgEgMAAgPIAAg+QAAgQAEgMQADgLAJgIQAHgGAKgEQAKgDANAAQAMAAALADQAKAEAIAGQAHAIAEALQAEAMAAAQIAAA+QAAAPgEAMQgEALgHAIQgIAGgKAEQgLACgMAAQgNAAgKgCgAhOg2QgEACgBAGQgBAEAAAHIAABGQAAAIABAFQABAFAEADQAFAEALABQAKgBAGgEQADgDACgFQABgFAAgIIAAhGQAAgHgBgEQgCgGgDgCQgGgGgKAAQgLAAgFAGgAI0BZIgdhJIgRAAIAABJIgiAAIAAiwIAyAAQAOAAAMAEQAMADAHAHQAHAHAEAKQADAJAAANIgBAQIgEAMQgEAGgEACQgGAFgHACIAhBQgAIGgKIASAAQALAAAGgGQADgDACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgGgGgLAAIgSAAgAGyBZIgJgmIgvAAIgKAmIggAAIAsiwIAsAAIAqCwgAGiAVIgRhGIAAAAIgRBGIAiAAgADhBZIAAiwIBdAAIAAAeIg8AAIAAAoIAtAAIAAAcIgtAAIAAAwIA+AAIAAAegAB8BZIAAhJIgwhnIAkAAIAeBHIAchHIAlAAIgxBnIAABJgAjQBZIgZh4IgBAAIgaB4IggAAIgliwIAeAAIAZByIABAAIAYhyIAgAAIAZByIAAAAIAYhyIAgAAIgnCwgAmeBZIAAiSIgnAAIAAgeIBxAAIAAAeIgoAAIAACSgApABZIg0hxIgBAAIAABxIgfAAIAAiwIAlAAIAvBnIABAAIAAhnIAgAAIAACwgArYBZIAAiwIAiAAIAACwg");
	this.shape_1.setTransform(0.1,-1.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AmrhNQgIAIgDALQgEAMAAAPIAAA/QAAAPAEAMQADAMAIAHQAHAHALADQAKADANAAQANAAAJgDQALgDAHgHQAIgHAEgMQAEgMAAgPIAAg/QAAgPgEgMQgEgLgIgIQgHgGgLgEQgJgDgNAAQgNAAgKADQgLAEgHAGgAmXgvQABgFAEgDQAFgFALAAQAKAAAGAFQADADABAFQACAFAAAHIAABHQAAAHgCAFQgBAFgDADQgGAFgKAAQgLAAgFgFQgEgDgBgFQgCgFAAgHIAAhHQAAgHACgFgAkNg7IASAAQALAAAGAGQADADACAFQACAEAAAGQAAAHgCAEQgCAFgDADQgGAGgLAAIgSAAgAjQhJQgIgHgLgEQgMgDgPAAIgxAAIAACwIAiAAIAAhJIAQAAIAeBJIAlAAIgihPQAHgDAFgFQAFgCADgGQAEgFABgIQACgHAAgIQAAgNgDgKQgFgKgHgGgAhhhXIAACwIBYAAIAAgeIg2AAIAAiSgACGgYQADAHAFAGQAFAFAIAFIANAHQAWAMAFAEQAFAEACAFQAEAFAAAGQAAAKgGAFQgFAGgKAAQgIAAgHgGQgEgEgDgGQgDgFgBgIIgiAHQAEANAGAKQAFAJAHAGQAIAGAJADQAJADALAAQANAAAKgEQAKgDAIgHQAHgGAEgKQAEgJAAgMQAAgJgDgJQgDgIgGgHQgEgFgIgEIgOgJQgSgKgIgFQgGgDgDgEQgDgFAAgEQAAgKAFgFQAFgFAJAAQAJAAAFAGQAHAGAEAMIAegJQgCgKgFgHQgEgIgHgGQgHgGgJgCQgJgEgLAAQgOAAgKAEQgKADgGAGQgHAHgDAKQgEAIAAAMQAAAJAEAHgABZAMIAAgdIguAAIAAgoIA7AAIAAgeIhcAAIAACwIBfAAIAAgeIg+AAIAAgvgAFOg4QAGAGAFAMIAegJQgCgKgFgHQgEgIgHgGQgHgGgKgCQgIgEgMAAQgNAAgKAEQgKADgHAGQgGAHgEAKQgDAIAAAMQAAAJADAHQADAHAGAGQAFAFAHAFIAOAHQAVAMAFAEQAGAEACAFQAEAFAAAGQAAAKgGAFQgGAGgJAAQgJAAgGgGQgEgEgDgGQgDgFgCgIIghAHQADANAGAKQAGAJAHAGQAIAGAIADQAKADAKAAQANAAALgEQAKgDAIgHQAHgGAEgKQAEgJAAgMQAAgJgDgJQgEgIgFgHQgFgFgHgEIgOgJQgTgKgHgFQgGgDgDgEQgEgFAAgEQAAgKAFgFQAFgFAKAAQAIAAAGAGgAG7A2IgjAAIAAAjIAjAAg");
	this.shape_2.setTransform(-2,24.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AEtBYQgKgDgHgGQgIgGgFgKQgGgKgDgMIAhgHQABAHAEAGQACAGAEADQAHAHAIAAQAKAAAGgGQAFgFAAgKQAAgGgDgFQgDgFgFgEQgFgFgWgLIgNgGQgHgFgGgFQgFgHgDgHQgEgHAAgJQAAgLAEgKQAEgJAHgHQAGgGAKgDQAKgDANgBQAMABAIADQAKADAHAFQAGAGAEAJQAFAGADALIgeAIQgFgMgGgGQgGgFgIgBQgJAAgGAGQgEAEAAAKQgBAEAEAFQADAEAFADIAbAQIAOAIQAHAEAFAFQAFAHAEAIQACAIAAAKQAAAMgDAJQgFAKgGAGQgIAHgKADQgLAEgNgBQgLABgIgDgACkBYQgJgDgHgGQgIgGgGgKQgFgKgEgMIAigHQABAHADAGQADAGADADQAIAHAIAAQAKAAAFgGQAGgFAAgKQAAgGgDgFQgDgFgFgEQgFgFgWgLIgNgGQgIgFgFgFQgGgHgDgHQgDgHAAgJQAAgLADgKQAEgJAHgHQAGgGAKgDQAKgDAOgBQAKABAKADQAJADAHAFQAHAGAEAJQAFAGACALIgeAIQgEgMgHgGQgFgFgJgBQgJAAgFAGQgFAEAAAKQAAAEADAFQADAEAGADIAaAQIAOAIQAHAEAFAFQAGAHADAIQADAIAAAKQAAAMgEAJQgEAKgHAGQgIAHgKADQgKAEgNgBQgLABgJgDgAmZBYQgLgEgGgGQgJgIgDgLQgEgMAAgPIAAg+QAAgQAEgMQADgLAJgIQAGgGALgEQALgDAMAAQANAAAKADQAKAEAIAGQAHAIAEALQAEAMAAAQIAAA+QAAAPgEAMQgEALgHAIQgIAGgKAEQgKACgNAAQgMAAgLgCgAmSg2QgDACgCAGQgBAEAAAHIAABGQAAAIABAFQACAFADADQAFAEALABQALgBAFgEQADgDACgFQABgFAAgIIAAhGQAAgHgBgEQgCgGgDgCQgFgGgLAAQgLAAgFAGgAGYBZIAAgkIAjAAIAAAkgAAKBZIAAiwIBdAAIAAAeIg8AAIAAAoIAtAAIAAAcIgtAAIAAAwIA+AAIAAAegAhhBZIAAiwIAiAAIAACSIA2AAIAAAegAjfBZIgehJIgQAAIAABJIghAAIAAiwIAwAAQAQAAALAEQALADAIAHQAHAHAEAKQAEAJAAANQAAAIgBAIIgGAMQgDAGgFACQgFAFgHACIAhBQgAkNgKIASAAQAMAAAFgGQADgDACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgFgGgMAAIgSAAg");
	this.shape_3.setTransform(-2,24.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("ALAgCIgNgJQgTgKgIgFQgGgDgCgEQgEgFAAgEQAAgKAFgFQAFgFAJAAQAJAAAGAGQAGAGAEAMIAfgJQgDgKgEgHQgFgIgGgGQgHgGgKgCQgJgEgLAAQgNAAgKAEQgKADgHAGQgGAHgEAKQgDAIAAAMQAAAJADAHQADAHAFAGQAFAFAIAFIANAHQAWAMAFAEQAFAEADAFQADAFAAAGQAAAKgGAFQgFAGgKAAQgIAAgHgGQgEgEgDgGQgDgFgBgIIghAHQADANAGAKQAFAJAIAGQAHAGAJADQAJADALAAQANAAALgEQAKgDAHgHQAHgGAEgKQAEgJAAgMQAAgJgDgJQgDgIgGgHQgEgFgIgEgAo/hXIAABnIgBAAIgvhnIglAAIAACwIAfAAIAAhxIABAAIA0BxIAgAAIAAiwgArYhXIAACwIAiAAIAAiwgAmeg5IAACSIAiAAIAAiSIAoAAIAAgeIhyAAIAAAegAkrhXIgfAAIAlCwIAhAAIAah4IABAAIAZB4IAgAAIAoiwIggAAIgYByIAAAAIgZhyIggAAIgZByIAAAAgAh2AgQAAAPADAMQAEAMAIAHQAHAHALADQAKADANAAQAMAAAKgDQALgDAHgHQAIgHAEgMQADgMAAgPIAAg/QAAgPgDgMQgEgLgIgIQgHgGgLgEQgKgDgMAAQgNAAgKADQgLAEgHAGQgIAIgEALQgDAMAAAPgAgogjIAABHQAAAHgCAFQgBAFgDADQgGAFgKAAQgLAAgGgFQgDgDgBgFQgCgFAAgHIAAhHQAAgHACgFQABgFADgDQAGgFALAAQAKAAAGAFQADADABAFQACAFAAAHgABwhXIgkAAIAwBoIAABIIAiAAIAAhIIAxhoIglAAIgcBHgAECg5IA7AAIAAgeIhcAAIAACwIBfAAIAAgeIg+AAIAAgvIAtAAIAAgdIgtAAgAF7hXIgsCwIAhAAIAKgmIAvAAIAIAmIAhAAIgriwgAGRgxIAAAAIAQBGIghAAgAIwhUQgMgDgPAAIgxAAIAACwIAiAAIAAhJIAQAAIAeBJIAkAAIghhPQAHgDAFgFQAFgCADgGQADgFACgIQABgHAAgIQAAgNgDgKQgEgKgHgGQgIgHgLgEgAIwgjQAAAHgCAEQgCAFgDADQgGAGgLAAIgSAAIAAgxIASAAQALAAAGAGQADADACAFQACAEAAAGg");
	this.shape_4.setTransform(0.1,-1.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AKMBYQgJgDgHgGQgHgGgGgKQgGgKgDgMIAhgHQACAHADAGQACAGAFADQAGAHAIAAQAKAAAFgGQAGgFABgKQAAgGgEgFQgDgFgFgEQgFgFgWgLIgNgGQgHgFgFgFQgGgHgCgHQgEgHAAgJQAAgLAEgKQADgJAHgHQAGgGAKgDQAKgDANgBQAMABAIADQAKADAHAFQAGAGAFAJQAFAGACALIgeAIQgFgMgGgGQgFgFgKgBQgJAAgEAGQgGAEAAAKQABAEADAFQADAEAFADIAbAQIAOAIQAHAEAEAFQAHAHACAIQADAIAAAKQAAAMgDAJQgFAKgGAGQgIAHgKADQgLAEgNgBQgKABgKgDgAhVBYQgKgEgHgGQgJgIgDgLQgEgMAAgPIAAg+QAAgQAEgMQADgLAJgIQAHgGAKgEQAKgDANAAQAMAAALADQAKAEAIAGQAHAIAEALQAEAMAAAQIAAA+QAAAPgEAMQgEALgHAIQgIAGgKAEQgLACgMAAQgNAAgKgCgAhOg2QgEACgBAGQgBAEAAAHIAABGQAAAIABAFQABAFAEADQAFAEALABQAKgBAGgEQADgDACgFQABgFAAgIIAAhGQAAgHgBgEQgCgGgDgCQgGgGgKAAQgLAAgFAGgAI0BZIgdhJIgRAAIAABJIgiAAIAAiwIAyAAQAOAAAMAEQAMADAHAHQAHAHAEAKQADAJAAANIgBAQIgEAMQgEAGgEACQgGAFgHACIAhBQgAIGgKIASAAQALAAAGgGQADgDACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgGgGgLAAIgSAAgAGyBZIgJgmIgvAAIgKAmIggAAIAsiwIAsAAIAqCwgAGiAVIgRhGIAAAAIgRBGIAiAAgADhBZIAAiwIBdAAIAAAeIg8AAIAAAoIAtAAIAAAcIgtAAIAAAwIA+AAIAAAegAB8BZIAAhJIgwhnIAkAAIAeBHIAchHIAlAAIgxBnIAABJgAjQBZIgZh4IgBAAIgaB4IggAAIgliwIAeAAIAZByIABAAIAYhyIAgAAIAZByIAAAAIAYhyIAgAAIgnCwgAmeBZIAAiSIgnAAIAAgeIBxAAIAAAeIgoAAIAACSgApABZIg0hxIgBAAIAABxIgfAAIAAiwIAlAAIAvBnIABAAIAAhnIAgAAIAACwgArYBZIAAiwIAiAAIAACwg");
	this.shape_5.setTransform(0.1,-1.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.8,-12.3,147.8,46.8);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2C4F67").s().p("AifAGIAAgLIE/AAIAAALg");
	this.shape.setTransform(-461.4,463.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2C4F67").s().p("ApACJQAKgHARgQQAQgRgKAHIgCABQgOAHgrAHQgMgMgLgPQAfgIAfgTQARgKAJgIQBSgRArAGQAXADAGAGQgJhBhKAaQgXAJgaARQgOAIgIAHQgnAMgfABQgWABgPgEQgJgbgBgcQAbAoBBgdQAhgNAbgVQBBgPAtAIQAWAEAJAHQgHhDhGAZQgVAIgZAQQgWAPAEgBQhBAPgqACQgeACgPgFQACgdALgaQAcAjA4gXQAfgMAdgYQBLgPAuAHQAeAEAMAMQAUAmAAAoQAABEgyAxQgyAxhGAAQg3AAglgdgAmxBpQgJgygxARQgOAFgQALQgPALAEgBQAvgJAeAHQAQAEAGAFIAAAAgADxCZIAAgHIADAAQAFAAABgDIABgEIgKgiIAJAAIAFAWIAAAAIAGgWIAJAAIgLAjQgDAIgDADQgDACgFAAgABJCRQABgHAGAAIgDgCQgBAAAAgBQgBAAAAAAQAAgBAAgBQgBAAAAgBQABgEAFgCQgFgEAAgFQAAgFAEgEQADgEAHAAQAFAAAEADQACgDAGAAIAAAGIgGABQACACAAAEQAAAFgDADQgEAEgGAAQgGAAgBACQAAACAMABQAMABAAAIQAAAEgFADQgDADgJAAQgPAAgBgIgABRCQQAAAEAKAAQADAAADgCQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAQAAgEgKAAQgHAAAAAEgABUBwQAAABAAAAQAAAAgBABQAAAAAAABQAAABAAAAQAAAGAGAAQAGAAAAgGQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAQAAABgBAAgAAjCXIADgLIgEAAIAAgJIAKAAIAAAJIgFALgAGnCIQgFgFABgIQgBgJAFgFQAEgFAHAAQAHAAAEAFQAEAFAAAHIAAADIgVAAQAAAKAGAAQAFAAADgEIAHAEQgFAHgKAAQgHAAgEgFgAGsB2IANAAQgBgIgGAAQgHAAABAIgAFrCIQgEgFAAgIQAAgJAEgFQAFgFAHAAQAHAAAEAFQADAFAAAHIAAADIgVAAQAAAKAHAAQAFAAADgEIAGAEQgFAHgJAAQgHAAgFgFgAFwB2IANAAQAAgIgGAAQgHAAAAAIgACqCKQgDgDAAgDQAAgMAUgCIAAgDQAAgFgFAAQgFAAgDAFIgFgEQABgDAEgCQAEgCAEAAQAHABADADQAEADAAAHIAAARIABAFIgJAAIAAgDQgGAEgFAAQgFAAgCgDgACzB+QgDABAAADQAAAFADAAQAEAAAEgEIAAgIIgIADgAByCIQgFgFAAgIQAAgJAFgFQAEgFAHAAQAIAAADAFQAFAFAAAJQAAAIgFAFQgDAFgIAAQgHAAgEgFgAB2B7QABALAGAAQAHAAAAgLQAAgMgHAAQgGAAgBAMgAAACIQgDgFgBgIQABgJADgFQADgFAHAAQAHAAAEAFQADAFABAHIAAADIgWAAQABAKAGAAQAFAAADgEIAHAEQgGAHgKAAQgGAAgDgFgAADB2IAOAAQgBgIgGAAQgHAAAAAIgAg7CIQgEgFAAgIQAAgJAEgFQAEgFAIAAQAGAAAFAFQADAFAAAHIAAADIgVAAQAAAKAHAAQAEAAAEgEIAGAEQgFAHgJAAQgIAAgEgFgAg2B2IANAAQAAgIgGAAQgHAAAAAIgAjWCIQgDgFAAgIQAAgJADgFQAFgFAHAAQAHAAAFAFQADAFAAAJQAAAIgDAFQgFAFgHAAQgHAAgFgFgAjRB7QAAALAHAAQAHAAAAgLQAAgMgHAAQgHAAAAAMgAHKCMIAAgJIAJAAIAAAJgAGNCMIAAgjIAIAAIAAAGQADgGAGgBIAAAJIgBAAQgCAAgDADIgDADIAAAVgAFXCMIAAgXQABgGgFAAQgFAAgCAEIAAAZIgJAAIAAgxIAJAAIAAASQAFgFAEAAQALAAAAAMIAAAYgAEsCMIgFgWIgGAWIgIAAIgJgjIAIAAIAGAWIAEgWIAIAAIAGAWIAEgWIAIAAIgJAjgADiCMIAAgXQAAgGgEAAQgFAAgDAEIAAAZIgIAAIAAgjIAHAAIAAAEQAIgFADAAQAKAAAAAMIAAAYgAgZCMIAAgjIAIAAIAAAGQADgGAHgBIAAAJIgBAAQgDAAgDADIgDADIAAAVgAhPCMIAAgXQAAgGgEAAQgEAAgDAEIAAAZIgJAAIAAgxIAJAAIAAASQAFgFAFAAQAKAAAAAMIAAAYgAiMCMIAAgYQAAgFgEAAQgDAAgFAEIAAAZIgIAAIAAgYQAAgFgDAAQgEAAgEAEIAAAZIgIAAIAAgjIAIAAIAAAEQAEgFAGAAQAHAAACAFQAFgFAHAAQAIAAAAALIAAAZgAjvCMIAAgjIAHAAIAAAGQAEgGAGgBIAAAJIgBAAQgDAAgDADIgCADIAAAVgAkVCMIAAgxIAgAAIAAAIIgXAAIAAAMIARAAIAAAIIgRAAIAAAVgAIIBtIAAgVIgBAAIgGAVIgEAAIgGgVIAAAVIgEAAIAAgaIAHAAIAFASIABAAIAEgSIAHAAIAAAagAHjBtIAAgWIgHAAIAAgEIASAAIAAAEIgHAAIAAAWgAIuAuQgFgGAAgKIAAgqQAAgJAFgGQAGgHALAAQAKAAAGAHQAGAHgBAKIAAAFIgNAAQAAgJgCgEQgDgDgEAAQgGAAgBAJIAAAqQAAAJAIAAQAHAAABgMIAAgIIgKAAIAAgMIAYAAIAAArIgHAAIgDgGQgHAIgHAAQgJAAgGgGgAFbAtQgGgGAAgJIAAgqQAAgJAGgGQAGgHAKAAQAMAAAFAHQAGAGAAAJIAAAqQAAAJgGAGQgFAHgMAAQgKAAgGgHgAFkgMIAAApQAAAKAHAAQAIAAAAgKIAAgpQAAgJgIAAQgHAAAAAJgAEeAtQgGgGAAgJIAAgqQAAgJAGgGQAFgHAMAAQAKAAAFAHQAGAGAAALIAAAGIgPAAIAAgHQAAgKgGAAQgJAAABAJIAAApQgBAKAJAAQAGAAAAgJIAAgKIAPAAIAAAKQAAAJgGAGQgFAHgKAAQgMAAgFgHgAAAAuQgGgGgBgLIAAg9IANAAIAAA+QAAAJAIAAQAIAAgBgJIAAg+IAPAAIAAA9QABALgHAGQgFAGgLAAQgKAAgEgGgAjTAtQgFgGAAgJIAAgqQAAgJAFgGQAHgHAKAAQAMAAAFAHQAGAGAAAJIAAAqQAAAJgGAGQgFAHgMAAQgKAAgHgHgAjKgMIAAApQABAKAHAAQAIAAAAgKIAAgpQAAgJgIAAQgHAAgBAJgAkPAtQgGgGAAgJIAAgqQAAgJAGgGQAFgHAMAAQAKAAAGAHQAFAHAAAKIAAAGIgPAAIAAgHQAAgKgGAAQgIAAAAAJIAAApQAAAKAIAAQAGAAAAgJIAAgKIAPAAIAAAKQAAAJgFAGQgGAHgKAAQgMAAgFgHgAJmAyIAAhSIAnAAIAAAMIgYAAIAAAUIASAAIAAANIgSAAIAAAZIAaAAIAAAMgAHyAyIAAhSIAoAAIAAAMIgZAAIAAAUIATAAIAAANIgTAAIAAAZIAaAAIAAAMgAHCAyIAAhSIAPAAIAABGIAWAAIAAAMgAGSAyIAAhSIAOAAIAABGIAXAAIAAAMgADRAyIAAgjIgSgvIAPAAIAKAgIAAAAIAKggIAPAAIgRAvIAAAjgACeAyIAAhGIgPAAIAAgMIArAAIAAAMIgOAAIAABGgAB0AyIAAhSIAPAAIAABSgABUAyIgSgzIAAAzIgNAAIAAhSIANAAIASAuIAAAAIAAguIAOAAIAABSgAgjAyIAAhAIgNBAIgHAAIgOhAIAABAIgMAAIAAhSIATAAIAKAvIAAAAIAKgvIAUAAIAABSgAhtAyIAAhAIgOBAIgHAAIgNhAIAAAAIAABAIgMAAIAAhSIATAAIAKAvIAKgvIAUAAIAABSgADAg5IgLgjIgHAAIAAAjIgOAAIAAhVIAUAAQAMAAAGAGQAHAGAAANQgBARgJAFIAMAmgACuhoIAFAAQAGAAADgDQACgDAAgHQAAgHgCgDQgDgDgGAAIgFAAgABpg5IAAhVIAnAAIAAANIgZAAIAAAWIATAAIAAAMIgTAAIAAAZIAaAAIAAANgABBg5IAAhIIgOAAIAAgNIArAAIAAANIgOAAIAABIgAAgg5IgDgTIgPAAIgEATIgLAAIANhVIASAAIAQBVgAAQhZIALAAIgGgkIAAAAgAgjg5IgKg4IgKA4IgNAAIgPhVIANAAIAJA2IAAAAIAKg2IALAAIALA2IAAAAIAIg2IANAAIgPBVgAiDg5IAAhVIAnAAIAAANIgYAAIAAAWIASAAIAAAMIgSAAIAAAZIAaAAIAAANgAjAg5IAAhVIAWAAQAXAAgBAaIAAAhQABAagXAAgAiyhFIAGAAQAFAAADgDQACgCAAgHIAAglQAAgHgCgCQgDgDgFAAIgGAAgAjhg5IAAhVIAOAAIAABVgAkLg5IAAhIIgOAAIAAgNIArAAIAAANIgOAAIAABIgAp9hIQAWgqAogZQApgaAxAAQAzAAAqAcQgoANgiASQgWAMgJAIQhHAQgqAAQgPAAgMgCg");
	this.shape_1.setTransform(-466.6,434.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2C4F67").s().p("AgcAXIASgEQAAAXAKgBQAFAAACgCQACgDAAgFQAAgFgBgDQgCgEgCgDIgFgHIgPgLQgGgFgDgGQgDgGAAgKQgBgNAJgHQAHgHANAAQAFgBAFACQAEACADACQAEADACAEIADAIIABAKIgRAEIgBgHIgBgFIgCgEIgDgCQgBgBAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQgEAAgDADQgCADAAAFQAAAFACAEIAHAHIANAMIAGAFIAFAIQADADABAGQACAEAAAGQgBAMgHAIQgIAHgNABQgcAAgBgjg");
	this.shape_2.setTransform(-394.4,484.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2C4F67").s().p("AgKA4QgGgDgEgDQgEgDgCgFQgCgEgBgGIgBgMIAAgmIABgNQABgGACgFQACgFAEgDQAEgDAGgCQAFgCAFABQAJAAAGABQAGADAEAEQADAFABAFQACAGAAAIIAAAKIgUAAIAAgKQAAgJgBgCQgBgGgIAAIgBAAIgCAAIgEACIgBADIgCAEIAAAEIAAAGIAAAtQAAALACAEQADAEAEAAIAFgBIACAAIACgDIABgDIABgDIAAgEIAAgFIAAgJIAUAAIAAAJIgBALIgDAJQgCAFgDADQgEADgFACQgFACgIAAQgFAAgFgCg");
	this.shape_3.setTransform(-401.7,484.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2C4F67").s().p("AgJA4IAAhvIATAAIAABvg");
	this.shape_4.setTransform(-407.5,484);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2C4F67").s().p("AAQA4IgahBIAABBIgSAAIAAhvIAOAAIAaA+IAAg+IARAAIAABvg");
	this.shape_5.setTransform(-413.2,484);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2C4F67").s().p("AgYAwQgHgJAAgTIAAgoQAAgJACgHQABgGAEgFQAEgFAGgCQAHgDAHABQARgBAIAKQAHAJAAASIAAAoQAAAJgBAGQgCAHgEAGQgEAFgGACQgHACgIABQgQAAgIgKgAgFgoIgDADIgCAGIAAAGIAAAyIAAAGIABAEIACAEIADACIAEABIAFgBIADgCIACgEIABgEIAAgGIAAgyIAAgGIgCgGQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQgDgBgDAAQgCAAgDABg");
	this.shape_6.setTransform(-420.9,484.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2C4F67").s().p("AALA4IgMgzIgJAAIAAAzIgUAAIAAhvIAaAAQAGAAAHABQAGACAFADQAFAEACAGQADAGAAAIQAAALgEAHQgDAGgHABIAQA4gAgKgHIAFAAQAHAAAEgEQAEgDAAgKQAAgJgEgEQgDgEgGAAIgHAAg");
	this.shape_7.setTransform(-428.5,484);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2C4F67").s().p("AgJA4IAAhgIgTAAIAAgPIA5AAIAAAPIgTAAIAABgg");
	this.shape_8.setTransform(-435.5,484);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2C4F67").s().p("AAOA4IgEgaIgSAAIgFAaIgTAAIAXhvIATAAIAXBvgAgGAQIANAAIgHgsg");
	this.shape_9.setTransform(-442.2,484);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2C4F67").s().p("AALA4IAAgzIgVAAIAAAzIgVAAIAAhvIAVAAIAAAvIAVAAIAAgvIAVAAIAABvg");
	this.shape_10.setTransform(-449.9,484);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2C4F67").s().p("AgLA4QgFgDgEgDQgDgDgDgFQgCgEgBgGIgBgMIAAgmIABgNQABgGACgFQADgFADgDQAEgDAFgCQAGgCAGABQAIAAAGABQAGADADAEQAEAFACAFQABAGAAAIIAAAKIgUAAIAAgKQAAgJgBgCQgCgGgGAAIgBAAIgDAAIgDACIgCADIgCAEIAAAEIAAAGIAAAtQAAALADAEQACAEAFAAIADgBIADAAIACgDIABgDIABgDIAAgEIAAgFIAAgJIAUAAIAAAJIgBALIgDAJQgCAFgDADQgEADgFACQgGACgGAAQgGAAgGgCg");
	this.shape_11.setTransform(-457.7,484.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2C4F67").s().p("AgWA4IAAhvIAtAAIAAAOIgZAAIAAAhIATAAIAAANIgTAAIAAAlIAaAAIAAAOg");
	this.shape_12.setTransform(-464.2,484);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2C4F67").s().p("AAXA4IgBhMIgQBMIgKAAIgRhMIgBBMIgQAAIAChvIAVAAIAPBOIAQhOIAVAAIACBvg");
	this.shape_13.setTransform(-472.2,484);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2C4F67").s().p("AgVA4IAehvIANAAIgeBvg");
	this.shape_14.setTransform(-479.8,484);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2C4F67").s().p("AgMA3QgFgCgEgDQgDgDgDgFIgDgLIAAgNIAAhKIATAAIAABLIABAIIAAAFIACAFIAEADQADACABAAQACAAADgCIADgDIACgFIABgFIABgIIAAhLIATAAIAABKIAAANIgDALQgDAFgDADQgEADgFACQgGACgHAAQgGAAgGgCg");
	this.shape_15.setTransform(-486.5,484.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#2C4F67").s().p("AgeA4IAAhvIAbAAQAIAAAHACQAHACAEAEQAEAFACAGQACAHAAAJIAAAnQAAAKgCAHQgCAGgEAFQgEAFgHACQgHACgIAAgAgJAqIAGAAIADgBIAEgBIADgDIABgDIABgEIAAgFIABgGIAAgnIgBgHIAAgFIgCgEIgCgCIgFgCIgDAAIgGAAg");
	this.shape_16.setTransform(-494.2,484);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2C4F67").s().p("AgWA4IAAhvIAtAAIAAAOIgZAAIAAAhIATAAIAAANIgTAAIAAAlIAZAAIAAAOg");
	this.shape_17.setTransform(-500.9,484);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#2C4F67").s().p("AgIAJIAAgRIARAAIAAARg");
	this.shape_18.setTransform(-505.6,488.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2C4F67").s().p("AgLA4QgFgDgEgDQgEgDgCgFQgCgEgBgGIgBgMIAAgmIABgNQABgGACgFQACgFAEgDQAEgDAFgCQAGgCAFABQAJAAAGABQAGADADAEQAEAFACAFQABAGAAAIIAAAKIgUAAIAAgKQAAgJgBgCQgCgGgGAAIgCAAIgCAAIgDACIgCADIgCAEIAAAEIAAAGIAAAtQAAALACAEQADAEAEAAIAFgBIACAAIACgDIABgDIABgDIAAgEIAAgFIAAgJIAUAAIAAAJIgBALIgDAJQgCAFgDADQgEADgFACQgFACgIAAQgFAAgGgCg");
	this.shape_19.setTransform(-510.9,484.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#2C4F67").s().p("AgLA4QgFgDgEgDQgDgDgDgFQgCgEgBgGIgBgMIAAgmIABgNQABgGACgFQADgFADgDQAEgDAFgCQAGgCAGABQAIAAAGABQAGADADAEQAEAFACAFQABAGAAAIIAAAKIgUAAIAAgKQAAgJgBgCQgCgGgGAAIgBAAIgDAAIgDACIgCADIgCAEIAAAEIAAAGIAAAtQAAALADAEQACAEAFAAIADgBIADAAIACgDIABgDIABgDIAAgEIAAgFIAAgJIAUAAIAAAJIgBALIgDAJQgCAFgDADQgEADgFACQgGACgGAAQgGAAgGgCg");
	this.shape_20.setTransform(-518.4,484.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#2C4F67").s().p("AgJA4IAAhgIgTAAIAAgPIA5AAIAAAPIgTAAIAABgg");
	this.shape_21.setTransform(-525.2,484);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#91D2E5").s().p("As3IKIAAwTIZuAAIAAQTg");
	this.shape_22.setTransform(-461.3,455);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-543.7,402.7,164.8,104.5);


(lib.newFrame = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMIAAgXIAXAAIAAAXg");
	this.shape.setTransform(-7.3,115.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AghBBQgJgOAAgaIAAgwQAAgNACgKQACgKAFgHQAFgHAIgEQAJgDALAAQAWAAAKALQAKALAAAXIAAAHIgbAAIAAgIIAAgIIgBgHIgCgFIgFgDIgHgBIgEABIgEACIgDADIgBAFIgBAFIgBAFIAAAGIAAA9QAAANAEAHQADAGAIAAQAFAAADgCQADgBACgEIADgJIABgMIAAgNIgRAAIAAgQIAqAAIAABMIgSAAIgCgPQgHARgRAAQgWAAgKgNg");
	this.shape_1.setTransform(-14.7,109.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAVBMIgjhZIAABZIgZAAIAAiYIAUAAIAjBWIAAhWIAXAAIAACYg");
	this.shape_2.setTransform(-25.1,109.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMBMIAAiYIAZAAIAACYg");
	this.shape_3.setTransform(-32.9,109.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAPBMIgRhFIgMAAIAABFIgcAAIAAiYIAkAAQAJAAAJADQAJACAHAEQAGAFADAIQADAIAAAMQAAAOgEAKQgEAIgKACIAVBMgAgOgJIAHAAQAKAAAFgGQAGgFgBgNQAAgNgEgFQgEgFgKAAIgJAAg");
	this.shape_4.setTransform(-40.5,109.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQBLQgIgDgFgEQgFgEgDgHQgDgHgBgHIgBgTIAAhlIAbAAIAABnIABAKIABAIIACAHIAFADQADACADAAQAEAAADgCQADgBABgCIADgHIABgIIAAgKIAAhnIAcAAIAABlQAAAKgCAJQgBAHgDAHQgDAHgEAEQgFAEgIADQgHADgKAAQgJAAgHgDg");
	this.shape_5.setTransform(-51.4,109.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMBMIAAiCIgaAAIAAgWIBNAAIAAAWIgZAAIAACCg");
	this.shape_6.setTransform(-60.7,109.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPBMQgIgDgFgEQgFgFgDgGQgDgHgBgHQgBgIAAgKIAAgzQAAgKABgIQABgIADgGQADgHAFgEQAFgFAIgCQAIgCAIAAQALAAAIADQAIADAFAGQAFAGACAIQACAIAAAKIAAANIgbAAIAAgNQAAgLgBgEQgDgIgJgBIgBAAIgEABIgFADIgDAEIgBAFIgBAGIAAAHIAAA/QAAAOAEAGQADAFAHAAIAFAAIAEgCIACgDIACgEIABgFIAAgFIAAgGIAAgNIAbAAIAAAMQAAAJgBAHQgBAHgDAGQgDAGgFAEQgEAEgIACQgHACgJAAQgIAAgIgCg");
	this.shape_7.setTransform(-69.8,109.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AATBMIgGgjIgYAAIgHAjIgaAAIAfiYIAbAAIAfCYgAgJAWIATAAIgKg9g");
	this.shape_8.setTransform(-79.9,109.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBMIAAiYIA9AAIAAAUIghAAIAAAtIAaAAIAAASIgaAAIAABFg");
	this.shape_9.setTransform(-88.3,109.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQBLQgIgDgFgEQgFgEgDgHQgDgHgBgHIgBgTIAAhlIAbAAIAABnIABAKIABAIIACAHIAFADQADACADAAQAEAAADgCQADgBABgCIADgHIABgIIAAgKIAAhnIAcAAIAABlQAAAKgCAJQgBAHgDAHQgDAHgEAEQgFAEgIADQgHADgKAAQgJAAgHgDg");
	this.shape_10.setTransform(-98,109.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAWBMIgkhZIAABZIgZAAIAAiYIAUAAIAjBWIAAhWIAYAAIAACYg");
	this.shape_11.setTransform(-108.5,109.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATBMIgGgjIgYAAIgHAjIgaAAIAfiYIAbAAIAfCYgAgJAWIATAAIgKg9g");
	this.shape_12.setTransform(-118.6,109.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAgBMIgChnIgWBnIgOAAIgXhoIgCBoIgVAAIACiYIAdAAIAVBrIAWhrIAdAAIACCYg");
	this.shape_13.setTransform(-130,109.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgpBMIAAiYIAkAAQAMAAAJADQAKADAFAGQAGAHACAIQADAJAAAMIAAA2QAAANgDAJQgCAKgGAGQgFAHgJADQgJACgMAAgAgNA5IAIAAIAGgBIAFgBQAAgBABAAQAAAAABgBQAAAAABgBQAAAAAAgBIADgEIABgGIAAgHIAAgIIAAg3IAAgIIgBgHQAAgDgCgCIgDgDIgGgDIgGgBIgIAAg");
	this.shape_14.setTransform(-36.5,89.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgfBMIAAiYIA+AAIAAAUIgiAAIAAAsIAbAAIAAASIgbAAIAAAzIAjAAIAAATg");
	this.shape_15.setTransform(-45.5,89.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgPBMQgIgDgFgEQgFgFgDgGQgDgHgBgHQgBgIAAgKIAAgzQAAgKABgIQABgIADgGQADgHAFgEQAFgFAIgCQAIgCAIAAQALAAAIADQAIADAFAGQAFAGACAIQACAIAAAKIAAANIgbAAIAAgNQAAgLgBgEQgDgIgJgBIgBAAIgEABIgFADIgDAEIgBAFIgBAGIAAAHIAAA/QAAAOAEAGQADAFAHAAIAFAAIAEgCIACgDIACgEIABgFIAAgFIAAgGIAAgNIAbAAIAAAMQAAAJgBAHQgBAHgDAGQgDAGgFAEQgEAEgIACQgHACgJAAQgIAAgIgCg");
	this.shape_16.setTransform(-55,89.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAWBMIgkhZIAABZIgZAAIAAiYIAUAAIAjBWIAAhWIAYAAIAACYg");
	this.shape_17.setTransform(-65.3,89.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AATBMIgGgjIgYAAIgHAjIgaAAIAfiYIAbAAIAfCYgAgJAWIATAAIgKg9g");
	this.shape_18.setTransform(-75.4,89.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgMBMIgfiYIAYAAIATBqIAThqIAZAAIgfCYg");
	this.shape_19.setTransform(-85.2,89.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgpBMIAAiYIAkAAQAMAAAJADQAKADAFAGQAGAHACAIQADAJAAAMIAAA2QAAANgDAJQgCAKgGAGQgFAHgJADQgJACgMAAgAgNA5IAIAAIAGgBIAFgBQAAgBABAAQAAAAABgBQAAAAABgBQAAAAAAgBIADgEIABgGIAAgHIAAgIIAAg3IAAgIIgBgHQAAgDgCgCIgDgDIgGgDIgGgBIgIAAg");
	this.shape_20.setTransform(-95.2,89.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AATBMIgGgjIgYAAIgHAjIgaAAIAfiYIAbAAIAfCYgAgJAWIATAAIgKg9g");
	this.shape_21.setTransform(-105.5,89.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAVBNIgkhaIAABaIgYAAIAAiYIAUAAIAkBVIAAhVIAWAAIAACYg");
	this.shape_22.setTransform(-15.4,69.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgMBNIAAiYIAZAAIAACYg");
	this.shape_23.setTransform(-23.1,69.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgnAfIAYgFQABAfAPAAQAGAAADgEQADgEAAgHQAAgGgCgFQgCgGgDgDIgHgJIgUgPQgJgIgFgIQgEgJAAgMQAAgSALgKQAKgKASAAQAHAAAGACQAHACAEAEQAEADADAGQADAFABAGIACANIgYAFIAAgIIgCgHIgCgGIgFgDQgCgCgCABQgGAAgDAEQgEAEAAAGQAAAHADAFQADAFAGAFIASASIAJAHIAHAJQAEAGABAGQACAHAAAHQAAARgLALQgKAKgRAAQgnAAgCgvg");
	this.shape_24.setTransform(-34.9,69.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAPBNIgQhGIgNAAIAABGIgcAAIAAiYIAjAAQAKAAAJACQAJABAGAGQAHAEADAIQADAIAAALQAAAPgEAKQgFAJgJABIAVBNgAgOgKIAHAAQAKAAAFgFQAGgFAAgNQgBgMgEgGQgFgFgKAAIgIAAg");
	this.shape_25.setTransform(-44.8,69.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgfBNIAAiYIA/AAIAAAUIgjAAIAAAsIAbAAIAAASIgbAAIAAAyIAjAAIAAAUg");
	this.shape_26.setTransform(-54,69.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgfBNIAAiYIA/AAIAAAUIgjAAIAAAsIAbAAIAAASIgbAAIAAAyIAjAAIAAAUg");
	this.shape_27.setTransform(-62.1,69.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAPBNIgQhGIgNAAIAABGIgcAAIAAiYIAjAAQAKAAAJACQAJABAGAGQAGAEAEAIQADAIAAALQAAAPgEAKQgFAJgKABIAWBNgAgOgKIAHAAQAKAAAFgFQAFgFABgNQAAgMgFgGQgFgFgKAAIgIAAg");
	this.shape_28.setTransform(-71.5,69.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AATBNIgGgkIgYAAIgHAkIgaAAIAfiYIAbAAIAfCYgAgJAXIATAAIgKg9g");
	this.shape_29.setTransform(-82,69.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgPBMQgIgDgFgEQgFgFgDgGQgDgHgBgHQgBgIAAgKIAAgzQAAgKABgIQABgIADgGQADgHAFgEQAFgFAIgCQAIgCAIAAQALAAAIADQAIADAFAGQAFAGACAIQACAIAAAKIAAANIgbAAIAAgNQAAgLgBgEQgDgIgJgBIgBAAIgEABIgFADIgDAEIgBAFIgBAGIAAAHIAAA/QAAAOAEAGQADAFAHAAIAFAAIAEgCIACgDIACgEIABgFIAAgFIAAgGIAAgNIAbAAIAAAMQAAAJgBAHQgBAHgDAGQgDAGgFAEQgEAEgIACQgHACgJAAQgIAAgIgCg");
	this.shape_30.setTransform(-92,69.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgMBNIAAiDIgaAAIAAgVIBNAAIAAAVIgZAAIAACDg");
	this.shape_31.setTransform(-105.8,69.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AggBBQgLgNAAgZIAAg2QAAgNADgJQACgJAFgGQAFgHAJgDQAIgDALAAQAXAAALAMQAKANAAAZIAAA2QAAANgCAJQgDAJgFAHQgFAGgJAEQgIADgMAAQgWAAgKgNgAgHg3QgDACgCADIgCAHIAAAJIAABEIAAAIIABAGIADAFIAFADIAFABIAHgBIAEgDIADgFIABgGIAAgIIAAhEIAAgJIgCgHQgCgDgDgCQgDgCgFAAQgDAAgEACg");
	this.shape_32.setTransform(-115.1,69.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAPBNIAAhGIgdAAIAABGIgcAAIAAiYIAcAAIAABAIAdAAIAAhAIAcAAIAACYg");
	this.shape_33.setTransform(-126,69.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-138.5,54.1,135.3,75.8);


(lib.mechanics = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAUQAHgCAFgFQADgGAAgHIgQAAIAAggIAfAAIAAAeQAAAdgaAGg");
	this.shape.setTransform(49,22.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_1.setTransform(39.1,11.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUBkQgKgEgGgFQgHgHgEgIQgFgJgBgKQgBgKAAgMIAAhEQAAgOABgKQACgKAEgJQAEgIAHgGQAGgGAKgDQAKgDALAAQAPAAALAEQALAEAGAHQAGAJADAKQADAKgBAPIAAARIgjAAIAAgRQAAgQgCgFQgCgLgNAAIgCAAIgGABQgEABgBADIgFAEIgBAHIgBAIIAAAKIAABUQgBARAFAIQAEAHAKAAIAHgBIAFgBIAEgFIABgEIABgHIABgHIAAgHIAAgSIAjAAIAAAQQABAMgCAJQgBAIgFAJQgDAIgHAEQgFAGgKADQgKADgMAAQgLAAgKgDg");
	this.shape_2.setTransform(25.1,12);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpBlIAAjJIBTAAIAAAaIguAAIAAA6IAkAAIAAAYIgkAAIAABDIAuAAIAAAag");
	this.shape_3.setTransform(13.4,11.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQBlIAAitIgiAAIAAgcIBlAAIAAAcIggAAIAACtg");
	this.shape_4.setTransform(2.4,11.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdALIAAgVIA7AAIAAAVg");
	this.shape_5.setTransform(-7.3,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_6.setTransform(-19,11.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrBVQgNgSAAgiIAAhAQAAgSADgMQADgMAGgKQAHgKALgEQALgFAPAAQAeAAANAPQANAOAAAeIAAAKIgjAAIAAgKIgBgLIgBgJQgBgEgDgCQgCgDgEgCQgDgBgGAAIgFABIgGADIgDAEIgDAGIgBAGIAAAHIgBAIIAABQQAAATAFAIQAEAIALAAQAHABAEgDQAFgDACgFQADgEABgHIABgQIAAgRIgWAAIAAgVIA3AAIAABkIgYAAIgDgUQgJAXgXAAQgdAAgMgSg");
	this.shape_7.setTransform(-33.4,12);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgRBlIAAjJIAjAAIAADJg");
	this.shape_8.setTransform(-43.7,11.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_9.setTransform(-54.4,11.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.8,-7.2,117.5,38);


(lib.jobs = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPARIAAggIAfAAIAAAgg");
	this.shape.setTransform(-41.5,12.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0ApIAggGQABAoAUAAQAIAAAFgFQADgFAAgJQAAgIgCgHQgDgIgFgEIgJgLIgagVQgMgKgGgLQgFgLgBgRQAAgYAOgNQAOgNAYAAQAJAAAJADQAIADAGAFQAGAEADAHQAEAIABAIIAEARIggAGIgBgLIgCgJQgBgEgDgDQgBgDgEgCQgEgCgCABQgJAAgEAFQgEAFgBAIQAAAKAEAHQAFAGAIAHIAYAXIALAKIAKAMQAEAIADAIQACAJAAAKQAAAWgOANQgOAOgXAAQgzAAgDg+g");
	this.shape_1.setTransform(-50.3,3.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag4BlIAAjJIAyAAQALAAALADQAKACAJAGQAIAGAEAKQAEAKAAAPQAAAlgeAFQASADAJALQAJAMAAAWQAAAdgPAPQgOAPgcAAgAgTBLIAOAAQAOAAAGgIQAHgIgBgRQABgTgIgIQgGgIgPAAIgMAAgAgTgRIAMAAQANAAAHgHQAGgHAAgRQAAgIgCgFQgCgGgFgCQgFgDgFgBIgOgBIgFAAg");
	this.shape_2.setTransform(-63.3,3.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrBWQgOgRAAghIAAhJQAAgPADgNQADgLAHgJQAHgIALgFQALgEAPAAQAfAAANARQAOAQAAAgIAABJQAAAQgDAMQgDAMgHAJQgHAJgLAEQgMAFgPAAQgeAAgNgRgAgJhJQgFACgCAFIgDAJIAAAMIAABaIAAAKIACAIQABAEACADQACADAEABQAEABAEABQAFgBAEgBIAGgEIADgHIACgIIAAgKIAAhaIAAgMIgDgJQgCgFgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_3.setTransform(-77.6,3.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeBnIAAgaQAQAAAFgFQAGgFAAgQIAAiZIAiAAIAACaQAAANgCAKQgCAJgFAHQgFAGgJADQgIADgNAAg");
	this.shape_4.setTransform(-89.3,4.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag2BlIAAjJIAvAAQAQAAANAEQAMAEAHAIQAIAIADALQADAMAAAQIAABHQAAASgDAMQgDAMgHAIQgIAJgMAEQgMAEgQAAgAgRBLIAKAAIAIgBIAHgCQADgCACgDIACgFIACgIIAAgJIABgLIAAhIIgBgLIgBgJIgCgHIgFgFQgDgCgEAAIgJgBIgKAAg");
	this.shape_5.setTransform(-4.3,-21.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAcBlIgwh3IAAB3IgfAAIAAjJIAZAAIAwBxIAAhxIAeAAIAADJg");
	this.shape_6.setTransform(-18.2,-21.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAaBlIgIgvIgiAAIgIAvIgjAAIAqjJIAkAAIApDJgAgMAeIAZAAIgNhRg");
	this.shape_7.setTransform(-31.5,-21.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAqBlIgDiKIgdCKIgTAAIgeiKIgCCKIgcAAIADjJIAmAAIAcCNIAdiNIAlAAIAEDJg");
	this.shape_8.setTransform(-46.4,-21.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgpBlIAAjJIBTAAIAAAaIguAAIAAA6IAkAAIAAAYIgkAAIAABDIAuAAIAAAag");
	this.shape_9.setTransform(-59.9,-21.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2BlIAAjJIAvAAQAQAAANAEQAMAEAHAIQAIAIADALQADAMAAAQIAABHQAAASgDAMQgDAMgHAIQgIAJgMAEQgMAEgQAAgAgRBLIAKAAIAIgBIAHgCQADgCACgDIACgFIACgIIAAgJIABgLIAAhIIgBgLIgBgJIgCgHIgFgFQgDgCgEAAIgJgBIgKAAg");
	this.shape_10.setTransform(-72.4,-21.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgdALIAAgVIA7AAIAAAVg");
	this.shape_11.setTransform(-83.9,-19);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_12.setTransform(-95.6,-21.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrBVQgNgSAAgiIAAhAQAAgSADgMQADgNAGgJQAHgKALgEQALgFAPAAQAeAAANAPQANAOAAAeIAAAKIgjAAIAAgKIgBgMIgBgIQgBgEgDgCQgCgDgEgCQgDgBgGAAIgFABIgGACIgDAFIgDAGIgBAGIAAAHIgBAIIAABQQAAASAFAJQAEAIALAAQAHAAAEgCQAFgDACgEQADgFABgHIABgQIAAgRIgWAAIAAgWIA3AAIAABmIgYAAIgDgVQgJAXgXAAQgdAAgMgSg");
	this.shape_13.setTransform(-110,-21.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRBlIAAjJIAjAAIAADJg");
	this.shape_14.setTransform(-120.3,-21.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_15.setTransform(-131,-21.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.4,-40.2,145,71.9);


(lib.image = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._300x250();
	this.instance.setTransform(-71.8,355.8,0.814,0.814);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.8,355.8,244.2,203.5);


(lib._if = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAUQAHgCAFgFQADgGAAgHIgQAAIAAggIAfAAIAAAeQAAAdgaAGg");
	this.shape.setTransform(122,28.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgrBVQgNgSAAgiIAAhAQAAgRADgNQADgNAGgJQAHgJALgGQALgEAPAAQAeAAANAPQANAOAAAeIAAAKIgjAAIAAgLIgBgLIgBgIQgBgFgDgBQgCgDgEgCQgDgBgGAAIgFABIgGACIgDAFIgDAFIgBAHIAAAIIgBAIIAABPQAAASAFAJQAEAJALAAQAHgBAEgCQAFgDACgEQADgGABgGIABgQIAAgQIgWAAIAAgXIA3AAIAABmIgYAAIgDgVQgJAXgXAAQgdAAgMgSg");
	this.shape_1.setTransform(112.3,18);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBlIgwh3IAAB3IgfAAIAAjJIAZAAIAwBxIAAhxIAeAAIAADJg");
	this.shape_2.setTransform(98.6,17.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRBlIAAjJIAjAAIAADJg");
	this.shape_3.setTransform(88.4,17.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQBlIAAhNIgph8IAiAAIAXBRIAYhRIAiAAIgpB8IAABNg");
	this.shape_4.setTransform(78.9,17.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaBlIgIgvIgiAAIgIAvIgjAAIAqjJIAkAAIApDJgAgMAeIAZAAIgNhRg");
	this.shape_5.setTransform(66.2,17.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag1BlIAAjJIA4AAQAzAAABA6QgBAcgOANQgOALgZAAIgRAAIAABbgAgQgOIALAAQAOAAAFgGQAGgGAAgQIgBgPQgBgFgCgEQgDgEgFgCQgFgCgIAAIgLAAg");
	this.shape_6.setTransform(53.8,17.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdALIAAgVIA7AAIAAAVg");
	this.shape_7.setTransform(42.4,20.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_8.setTransform(30.7,17.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgrBVQgNgSAAgiIAAhAQAAgRADgNQADgNAGgJQAHgJALgGQALgEAPAAQAeAAANAPQANAOAAAeIAAAKIgjAAIAAgLIgBgLIgBgIQgBgFgDgBQgCgDgEgCQgDgBgGAAIgFABIgGACIgDAFIgDAFIgBAHIAAAIIgBAIIAABPQAAASAFAJQAEAJALAAQAHgBAEgCQAFgDACgEQADgGABgGIABgQIAAgQIgWAAIAAgXIA3AAIAABmIgYAAIgDgVQgJAXgXAAQgdAAgMgSg");
	this.shape_9.setTransform(16.3,18);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRBlIAAjJIAjAAIAADJg");
	this.shape_10.setTransform(6,17.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUBlIAAhcIgnAAIAABcIglAAIAAjJIAlAAIAABVIAnAAIAAhVIAlAAIAADJg");
	this.shape_11.setTransform(-4.7,17.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.1,-1.2,140.8,38);


(lib.CTA = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape.setTransform(-28.8,122.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_1.setTransform(-37.8,122.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA+QgLgMAAgYIAAg0QABgLACgJQACgIAFgHQAEgGAJgDQAIgDAKAAQAWAAAKAMQAKAMAAAXIAAA0QAAALgCAJQgDAJgFAGQgFAHgIADQgIADgLAAQgVAAgJgMgAgHg0QgDACgBADIgCAGIgBAJIAABAIABAHIABAGIADAFQABACADABIAFABIAGgBQADgBABgCIADgFIACgGIAAgHIAAhAIgBgJIgCgGQgCgDgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_2.setTransform(-48,122.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAeBIIgBhiIgVBiIgOAAIgVhiIgCBiIgUAAIACiPIAcAAIATBkIAVhkIAbAAIACCPg");
	this.shape_3.setTransform(-59.3,122.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAUBIIgihUIAABUIgXAAIAAiPIASAAIAiBQIAAhQIAXAAIAACPg");
	this.shape_4.setTransform(-74.6,122.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAOBIIgQhCIgLAAIAABCIgbAAIAAiPIAiAAQAJAAAIABQAJACAGAFQAGAEADAIQADAHAAALQAAAOgEAJQgEAIgKACIAVBIgAgNgJIAGAAQAKAAAFgFQAFgFAAgMQAAgMgEgFQgFgFgJAAIgIAAg");
	this.shape_5.setTransform(-84.3,122.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASBIIgGgiIgXAAIgGAiIgZAAIAeiPIAZAAIAeCPgAgIAVIARAAIgJg6g");
	this.shape_6.setTransform(-94.2,122.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIA7AAIAAASIghAAIAAAqIAZAAIAAARIgZAAIAAAwIAhAAIAAASg");
	this.shape_7.setTransform(-102.4,122.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdBIIAAiPIAaAAIAAB9IAhAAIAAASg");
	this.shape_8.setTransform(-109.9,122.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// base
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#91D2E5").s().p("AqSClQgEAAgDgDQgDgDAAgEIAAk1QAAgEADgDQADgDAEAAIUlAAQAEAAADADQADADAAAEIAAE1QAAAEgDADQgDADgEAAgAqICRIURAAIAAkhI0RAAg");
	this.shape_9.setTransform(-69.6,123.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// hit
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(141,216,232,0)").s().p("AqSClQgEAAgDgDQgDgDAAgEIAAk1QAAgEADgDQADgDAEAAIUlAAQAEAAADADQADADAAAEIAAE1QAAAEgDADQgDADgEAAg");
	this.shape_10.setTransform(-69.6,123.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-136.5,106.8,134,33.1);


// stage content:
(lib._160x600 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_222 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(222).call(this.frame_222).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#1B1B1B").ss(1,1,1).p("EAMbguyMAAABdlI41AAMAAAhdlg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(223));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(150,132.9);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(158).to({y:98.1},0).to({y:76.9,alpha:1},11,cjs.Ease.get(1)).wait(54));

	// Layer 5
	this.instance_1 = new lib.Symbol17();
	this.instance_1.setTransform(635,101,1,1,0,0,0,93,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(223));

	// in 2 years
	this.instance_2 = new lib.twoyears();
	this.instance_2.setTransform(80.7,139.8,0.6,0.6);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(97).to({scaleX:1.05,scaleY:1.05,alpha:1},6).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(116));

	// high demand
	this.instance_3 = new lib.jobs();
	this.instance_3.setTransform(134.4,104.9);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(75).to({x:148.4,alpha:1},22).wait(126));

	// high tech
	this.instance_4 = new lib.mechanics();
	this.instance_4.setTransform(141.2,59.5,1,1,0,0,0,62.1,14);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(53).to({x:148.2,alpha:1},22,cjs.Ease.get(1)).wait(148));

	// high paying'
	this.instance_5 = new lib._if();
	this.instance_5.setTransform(65.9,25.1,1,1,0,0,0,48.3,12);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(31).to({x:72.9,alpha:1},22,cjs.Ease.get(1)).wait(170));

	// Layer 10
	this.instance_6 = new lib.newFrame();
	this.instance_6.setTransform(149.7,167.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(125).to({_off:false},0).to({alpha:1},18,cjs.Ease.get(1)).wait(80));

	// images
	this.instance_7 = new lib.image();
	this.instance_7.setTransform(150.7,61.7,1,1,0,0,0,150,125);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(7).to({alpha:1},21,cjs.Ease.get(1)).wait(195));

	// Layer 13
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#91D2E5").s().p("AsfIGIAAwLIY/AAIAAQLg");
	this.shape_1.setTransform(80,547.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2C4F67").s().p("EgMfAmuMAAAhNbIY/AAMAAABNbg");
	this.shape_2.setTransform(80,247.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(223));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8.8,254.7,408.5,645.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;